# Generated by Django 5.0.6 on 2024-05-31 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('WarhammerFantasyRoleplayVirtualGM_NPC', '0020_delete_adventure'),
        ('WarhammerFantasyRoleplayVirtualGM_app', '0058_alter_campaign_notes_alter_character_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adventure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='WarhammerFantasyRoleplayVirtualGM_app.campaign', verbose_name='Campaign')),
                ('npcs', models.ManyToManyField(blank=True, to='WarhammerFantasyRoleplayVirtualGM_NPC.npc', verbose_name='NPCs')),
            ],
        ),
    ]
