# Generated by Django 5.0.6 on 2024-07-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WarhammerFantasyRoleplayVirtualGM_Adventure', '0001_initial'),
        ('WarhammerFantasyRoleplayVirtualGM_app', '0062_alter_note_options_character_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventure',
            name='notes',
            field=models.ManyToManyField(blank=True, to='WarhammerFantasyRoleplayVirtualGM_app.note', verbose_name='Notes'),
        ),
    ]
