# Generated by Django 5.1 on 2024-09-09 18:52

import django.db.models.deletion
from django.db import migrations, models


def transfer_npcs(apps, schema_editor):
    Adventure = apps.get_model("WarhammerFantasyRoleplayVirtualGM_Adventure", "Adventure")
    Adventure2NPC = apps.get_model("WarhammerFantasyRoleplayVirtualGM_Adventure", "Adventure2NPC")
    
    adventures = Adventure.objects.all()
    for adv in adventures:
        for n in adv.npcs.all():
            adventure2NPC = Adventure2NPC.objects.create(npc=n, adventure=adv)
            adventure2NPC.save()
            print(adventure2NPC)

class Migration(migrations.Migration):

    dependencies = [
        ('WarhammerFantasyRoleplayVirtualGM_Adventure', '0002_adventure_notes'),
        ('WarhammerFantasyRoleplayVirtualGM_NPC', '0021_npc_ref'),
        ('WarhammerFantasyRoleplayVirtualGM_app', '0063_character_coruption_and_mutation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adventure',
            name='npcs',
            field=models.ManyToManyField(blank=True, related_name='old_npc', to='WarhammerFantasyRoleplayVirtualGM_NPC.npc', verbose_name='NPCs'),
        ),
        migrations.CreateModel(
            name='Adventure2NPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_wounds', models.IntegerField(default='0', verbose_name='Current Wounds')),
                ('adventure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WarhammerFantasyRoleplayVirtualGM_Adventure.adventure')),
                ('condition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WarhammerFantasyRoleplayVirtualGM_app.condition')),
                ('npc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WarhammerFantasyRoleplayVirtualGM_NPC.npc')),
            ],
        ),
        migrations.AddField(
            model_name='adventure',
            name='npcs2',
            field=models.ManyToManyField(blank=True, related_name='new_npc', through='WarhammerFantasyRoleplayVirtualGM_Adventure.Adventure2NPC', to='WarhammerFantasyRoleplayVirtualGM_NPC.npc', verbose_name='NPC2s'),
        ),
        migrations.RunPython(transfer_npcs, migrations.RunPython.noop),
    ]
