# Generated by Django 5.1 on 2024-09-09 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WarhammerFantasyRoleplayVirtualGM_Adventure', '0003_alter_adventure_npcs_adventure2npc_adventure_npcs2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adventure',
            name='npcs',
        ),
    ]
