# Generated by Django 5.1 on 2024-09-09 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WarhammerFantasyRoleplayVirtualGM_Adventure', '0004_remove_adventure_npcs'),
        ('WarhammerFantasyRoleplayVirtualGM_app', '0063_character_coruption_and_mutation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adventure2npc',
            name='condition',
        ),
        migrations.AddField(
            model_name='adventure2npc',
            name='condition',
            field=models.ManyToManyField(null=True, to='WarhammerFantasyRoleplayVirtualGM_app.condition'),
        ),
    ]
