# Generated by Django 5.1 on 2024-09-09 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WarhammerFantasyRoleplayVirtualGM_Adventure', '0006_adventure2npc_name'),
        ('WarhammerFantasyRoleplayVirtualGM_app', '0063_character_coruption_and_mutation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adventure2npc',
            name='condition',
            field=models.ManyToManyField(blank=True, null=True, to='WarhammerFantasyRoleplayVirtualGM_app.condition'),
        ),
        migrations.AlterField(
            model_name='adventure2npc',
            name='name',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
