# Generated by Django 3.2.19 on 2023-08-27 11:47

import WarhammerFantasyRoleplayVirtualGM_app.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('party_name', models.CharField(default='', max_length=250)),
                ('ambitions_shortterm', models.TextField(default='', verbose_name='Shortterm')),
                ('ambitions_longterm', models.TextField(default='', verbose_name='Longterm')),
            ],
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('random_table_human_start', models.IntegerField(default='0', verbose_name='random_table_human_start')),
                ('random_table_human_end', models.IntegerField(default='0', verbose_name='random_table_human_end')),
                ('random_table_dwarf_start', models.IntegerField(default='0', verbose_name='random_table_dwarf_start')),
                ('random_table_dwarf_end', models.IntegerField(default='0', verbose_name='random_table_dwarf_end')),
                ('random_table_halfling_start', models.IntegerField(default='0', verbose_name='random_table_halfling_start')),
                ('random_table_halfling_end', models.IntegerField(default='0', verbose_name='random_table_halfling_end')),
                ('random_table_high_elf_start', models.IntegerField(default='0', verbose_name='random_table_high_elf_start')),
                ('random_table_high_elf_end', models.IntegerField(default='0', verbose_name='random_table_high_elf_end')),
                ('random_table_wood_elf_start', models.IntegerField(default='0', verbose_name='random_table_wood_elf_start')),
                ('random_table_wood_elf_end', models.IntegerField(default='0', verbose_name='random_table_wood_elf_end')),
            ],
        ),
        migrations.CreateModel(
            name='CareerPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('earning_money', models.CharField(default='default', max_length=50, verbose_name='Earning Money')),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RefBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.IntegerField(default=0, verbose_name='Page')),
                ('refBook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WarhammerFantasyRoleplayVirtualGM_app.refbook', verbose_name='Reference Book')),
            ],
            options={
                'ordering': ['refBook', 'page'],
            },
        ),
        migrations.CreateModel(
            name='Skils',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('characteristics', models.CharField(default='', max_length=3)),
                ('description', models.TextField(default='', verbose_name='Description')),
                ('ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WarhammerFantasyRoleplayVirtualGM_app.reference')),
                ('skils_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='WarhammerFantasyRoleplayVirtualGM_app.skils')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Trapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(default='', verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Talent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('max', models.CharField(default='', max_length=50)),
                ('tests', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('description', models.TextField(default='', verbose_name='Description')),
                ('ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WarhammerFantasyRoleplayVirtualGM_app.reference')),
                ('talent_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='WarhammerFantasyRoleplayVirtualGM_app.talent')),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('random_interal_start', models.IntegerField(default=0, verbose_name='random_interal_start')),
                ('random_interal_end', models.IntegerField(default=0, verbose_name='random_interal_end')),
                ('skills', models.ManyToManyField(to='WarhammerFantasyRoleplayVirtualGM_app.Skils')),
                ('talents', models.ManyToManyField(to='WarhammerFantasyRoleplayVirtualGM_app.Talent')),
            ],
        ),
        migrations.CreateModel(
            name='RandomTalentsTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('random_interal_start', models.IntegerField(default=0, verbose_name='random_interal_start')),
                ('random_interal_end', models.IntegerField(default=0, verbose_name='random_interal_end')),
                ('any', models.BooleanField(default=False, verbose_name='Any')),
                ('talent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WarhammerFantasyRoleplayVirtualGM_app.talent', verbose_name='Talent')),
            ],
        ),
        migrations.CreateModel(
            name='RandomAttributesTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weapon_skill', models.IntegerField(default='0', verbose_name='weapon_skill')),
                ('ballistic_skill', models.IntegerField(default='0', verbose_name='ballistic_skill')),
                ('strength', models.IntegerField(default='0', verbose_name='strength')),
                ('toughness', models.IntegerField(default='0', verbose_name='toughness')),
                ('initiative', models.IntegerField(default='0', verbose_name='initiative')),
                ('agility', models.IntegerField(default='0', verbose_name='agility')),
                ('dexterity', models.IntegerField(default='0', verbose_name='dexterity')),
                ('intelligence', models.IntegerField(default='0', verbose_name='intelligence')),
                ('willpower', models.IntegerField(default='0', verbose_name='willpower')),
                ('fellowship', models.IntegerField(default='0', verbose_name='fellowship')),
                ('fate', models.IntegerField(default='0', verbose_name='fate')),
                ('resilience', models.IntegerField(default='0', verbose_name='resilience')),
                ('extra_points', models.IntegerField(default='0', verbose_name='extra_points')),
                ('movement', models.IntegerField(default='0', verbose_name='movement')),
                ('species', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WarhammerFantasyRoleplayVirtualGM_app.species', verbose_name='Species')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Player')),
            ],
        ),
        migrations.CreateModel(
            name='Hair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('random_table_start', models.IntegerField(default='0', verbose_name='random_table_human_start')),
                ('random_table_end', models.IntegerField(default='0', verbose_name='random_table_human_end')),
                ('species', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WarhammerFantasyRoleplayVirtualGM_app.species', verbose_name='Species')),
            ],
        ),
        migrations.CreateModel(
            name='Eyes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('random_table_start', models.IntegerField(default='0', verbose_name='random_table_human_start')),
                ('random_table_end', models.IntegerField(default='0', verbose_name='random_table_human_end')),
                ('species', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WarhammerFantasyRoleplayVirtualGM_app.species', verbose_name='Species')),
            ],
        ),
        migrations.CreateModel(
            name='ExampleName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('sex', models.CharField(default='f', max_length=1, validators=[WarhammerFantasyRoleplayVirtualGM_app.validators.validator_sex])),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WarhammerFantasyRoleplayVirtualGM_app.species')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Character name')),
                ('career_level', models.IntegerField(default='1', verbose_name='Career  Level')),
                ('age', models.IntegerField(default='1', verbose_name='Age')),
                ('height', models.IntegerField(default='1', verbose_name='Age')),
                ('characteristics_ws_initial', models.IntegerField(default='0', verbose_name='ws_initial')),
                ('characteristics_bs_initial', models.IntegerField(default='0', verbose_name='bs_initial')),
                ('characteristics_s_initial', models.IntegerField(default='0', verbose_name='s_initial')),
                ('characteristics_t_initial', models.IntegerField(default='0', verbose_name='t_initial')),
                ('characteristics_i_initial', models.IntegerField(default='0', verbose_name='i_initial')),
                ('characteristics_ag_initial', models.IntegerField(default='0', verbose_name='ag_initial')),
                ('characteristics_dex_initial', models.IntegerField(default='0', verbose_name='dex_initial')),
                ('characteristics_int_initial', models.IntegerField(default='0', verbose_name='int_initial')),
                ('characteristics_wp_initial', models.IntegerField(default='0', verbose_name='wp_initial')),
                ('characteristics_fel_initial', models.IntegerField(default='0', verbose_name='fel_initial')),
                ('characteristics_ws_advances', models.IntegerField(default='0', verbose_name='ws_advances')),
                ('characteristics_bs_advances', models.IntegerField(default='0', verbose_name='bs_advances')),
                ('characteristics_s_advances', models.IntegerField(default='0', verbose_name='s_advances')),
                ('characteristics_t_advances', models.IntegerField(default='0', verbose_name='t_advances')),
                ('characteristics_i_advances', models.IntegerField(default='0', verbose_name='i_advances')),
                ('characteristics_ag_advances', models.IntegerField(default='0', verbose_name='ag_advances')),
                ('characteristics_dex_advances', models.IntegerField(default='0', verbose_name='dex_advances')),
                ('characteristics_int_advances', models.IntegerField(default='0', verbose_name='int_advances')),
                ('characteristics_wp_advances', models.IntegerField(default='0', verbose_name='wp_advances')),
                ('characteristics_fel_advances', models.IntegerField(default='0', verbose_name='fel_advances')),
                ('wounds', models.IntegerField(default='0', verbose_name='wounds')),
                ('fate_fate', models.IntegerField(default='0', verbose_name='fate_fate')),
                ('fate_fortune', models.IntegerField(default='0', verbose_name='fate_fortune')),
                ('resilience_resilience', models.IntegerField(default='0', verbose_name='resilience_resilience')),
                ('resilience_resolve', models.IntegerField(default='0', verbose_name='resilience_resolve')),
                ('resilience_motivation', models.CharField(max_length=50, verbose_name='Character Motivation')),
                ('experience_current', models.IntegerField(default='0', verbose_name='experience_current')),
                ('experience_spent', models.IntegerField(default='0', verbose_name='experience_spent')),
                ('experience_total', models.IntegerField(default='0', verbose_name='experience_total')),
                ('movement_movement', models.IntegerField(default='0', verbose_name='movement_movement')),
                ('movement_walk', models.IntegerField(default='0', verbose_name='movement_walk')),
                ('movement_run', models.IntegerField(default='0', verbose_name='movement_run')),
                ('ambitions_shortterm', models.TextField(default='', verbose_name='Shortterm')),
                ('ambitions_longterm', models.TextField(default='', verbose_name='Longterm')),
                ('career', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WarhammerFantasyRoleplayVirtualGM_app.career', verbose_name='Career')),
                ('career_path', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WarhammerFantasyRoleplayVirtualGM_app.careerpath', verbose_name='CareerPath')),
                ('ch_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WarhammerFantasyRoleplayVirtualGM_app.class', verbose_name='Class')),
                ('eyes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WarhammerFantasyRoleplayVirtualGM_app.eyes', verbose_name='Eyes')),
                ('hair', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WarhammerFantasyRoleplayVirtualGM_app.hair', verbose_name='Hair')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WarhammerFantasyRoleplayVirtualGM_app.player', verbose_name='Player')),
                ('species', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WarhammerFantasyRoleplayVirtualGM_app.species', verbose_name='Species')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WarhammerFantasyRoleplayVirtualGM_app.status', verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='CareersAdvanceScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characteristics_ws_initial', models.CharField(choices=[('NO', ' '), ('CR', 'CROSS'), ('HA', 'HALBERD'), ('SK', 'SKULL'), ('SH', 'SHIELD')], default='NO', max_length=2, verbose_name='Weapon Skill')),
                ('characteristics_bs_initial', models.CharField(choices=[('NO', ' '), ('CR', 'CROSS'), ('HA', 'HALBERD'), ('SK', 'SKULL'), ('SH', 'SHIELD')], default='NO', max_length=2, verbose_name='Ballistic Skill')),
                ('characteristics_s_initial', models.CharField(choices=[('NO', ' '), ('CR', 'CROSS'), ('HA', 'HALBERD'), ('SK', 'SKULL'), ('SH', 'SHIELD')], default='NO', max_length=2, verbose_name='Strength')),
                ('characteristics_t_initial', models.CharField(choices=[('NO', ' '), ('CR', 'CROSS'), ('HA', 'HALBERD'), ('SK', 'SKULL'), ('SH', 'SHIELD')], default='NO', max_length=2, verbose_name='Toughness')),
                ('characteristics_i_initial', models.CharField(choices=[('NO', ' '), ('CR', 'CROSS'), ('HA', 'HALBERD'), ('SK', 'SKULL'), ('SH', 'SHIELD')], default='NO', max_length=2, verbose_name='Initiative')),
                ('characteristics_ag_initial', models.CharField(choices=[('NO', ' '), ('CR', 'CROSS'), ('HA', 'HALBERD'), ('SK', 'SKULL'), ('SH', 'SHIELD')], default='NO', max_length=2, verbose_name='Agility')),
                ('characteristics_dex_initial', models.CharField(choices=[('NO', ' '), ('CR', 'CROSS'), ('HA', 'HALBERD'), ('SK', 'SKULL'), ('SH', 'SHIELD')], default='NO', max_length=2, verbose_name='Dexterity')),
                ('characteristics_int_initial', models.CharField(choices=[('NO', ' '), ('CR', 'CROSS'), ('HA', 'HALBERD'), ('SK', 'SKULL'), ('SH', 'SHIELD')], default='NO', max_length=2, verbose_name='Intelligence')),
                ('characteristics_wp_initial', models.CharField(choices=[('NO', ' '), ('CR', 'CROSS'), ('HA', 'HALBERD'), ('SK', 'SKULL'), ('SH', 'SHIELD')], default='NO', max_length=2, verbose_name='Willpower')),
                ('characteristics_fel_initial', models.CharField(choices=[('NO', ' '), ('CR', 'CROSS'), ('HA', 'HALBERD'), ('SK', 'SKULL'), ('SH', 'SHIELD')], default='NO', max_length=2, verbose_name='Fellowship')),
                ('advances_level_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advances_level_1', to='WarhammerFantasyRoleplayVirtualGM_app.careerpath')),
                ('advances_level_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advances_level_2', to='WarhammerFantasyRoleplayVirtualGM_app.careerpath')),
                ('advances_level_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advances_level_3', to='WarhammerFantasyRoleplayVirtualGM_app.careerpath')),
                ('advances_level_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advances_level_4', to='WarhammerFantasyRoleplayVirtualGM_app.careerpath')),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WarhammerFantasyRoleplayVirtualGM_app.career', verbose_name='Career')),
            ],
            options={
                'ordering': ['career'],
            },
        ),
        migrations.AddField(
            model_name='careerpath',
            name='skills',
            field=models.ManyToManyField(to='WarhammerFantasyRoleplayVirtualGM_app.Skils'),
        ),
        migrations.AddField(
            model_name='careerpath',
            name='talents',
            field=models.ManyToManyField(to='WarhammerFantasyRoleplayVirtualGM_app.Talent'),
        ),
        migrations.AddField(
            model_name='careerpath',
            name='trappings',
            field=models.ManyToManyField(to='WarhammerFantasyRoleplayVirtualGM_app.Trapping'),
        ),
        migrations.AddField(
            model_name='career',
            name='ch_class',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='WarhammerFantasyRoleplayVirtualGM_app.class', verbose_name='Class'),
        ),
        migrations.CreateModel(
            name='Campaign2Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WarhammerFantasyRoleplayVirtualGM_app.campaign')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WarhammerFantasyRoleplayVirtualGM_app.player')),
            ],
        ),
        migrations.CreateModel(
            name='Character2Talent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taken', models.IntegerField(default='0', verbose_name='adv')),
                ('characters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WarhammerFantasyRoleplayVirtualGM_app.character')),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WarhammerFantasyRoleplayVirtualGM_app.talent')),
            ],
            options={
                'unique_together': {('characters', 'talent')},
            },
        ),
        migrations.CreateModel(
            name='Character2Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adv', models.IntegerField(default='0', verbose_name='adv')),
                ('is_basic_skill', models.BooleanField(default=False)),
                ('is_species_skill', models.BooleanField(default=False)),
                ('is_career_skill', models.BooleanField(default=False)),
                ('characters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WarhammerFantasyRoleplayVirtualGM_app.character')),
                ('skills', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WarhammerFantasyRoleplayVirtualGM_app.skils')),
            ],
            options={
                'unique_together': {('characters', 'skills')},
            },
        ),
    ]
