# Generated by Django 3.2.19 on 2023-07-30 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('party_name', models.CharField(default='', max_length=250)),
                ('ambitions_shortterm', models.TextField(default='', verbose_name='Shortterm')),
                ('ambitions_longterm', models.TextField(default='', verbose_name='Longterm')),
            ],
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CareerPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('career_level', models.IntegerField(default='1', verbose_name='Career  Level')),
                ('age', models.IntegerField(default='1', verbose_name='Age')),
                ('height', models.IntegerField(default='1', verbose_name='Age')),
                ('characteristics_ws_initial', models.IntegerField(default='0', verbose_name='ws_initial')),
                ('characteristics_bs_initial', models.IntegerField(default='0', verbose_name='bs_initial')),
                ('characteristics_s_initial', models.IntegerField(default='0', verbose_name='s_initial')),
                ('characteristics_t_initial', models.IntegerField(default='0', verbose_name='t_initial')),
                ('characteristics_i_initial', models.IntegerField(default='0', verbose_name='i_initial')),
                ('characteristics_ag_initial', models.IntegerField(default='0', verbose_name='ag_initial')),
                ('characteristics_dex_initial', models.IntegerField(default='0', verbose_name='dex_initial')),
                ('characteristics_int_initial', models.IntegerField(default='0', verbose_name='int_initial')),
                ('characteristics_wp_initial', models.IntegerField(default='0', verbose_name='wp_initial')),
                ('characteristics_fel_initial', models.IntegerField(default='0', verbose_name='fel_initial')),
                ('characteristics_ws_advances', models.IntegerField(default='0', verbose_name='ws_advances')),
                ('characteristics_bs_advances', models.IntegerField(default='0', verbose_name='bs_advances')),
                ('characteristics_s_advances', models.IntegerField(default='0', verbose_name='s_advances')),
                ('characteristics_t_advances', models.IntegerField(default='0', verbose_name='t_advances')),
                ('characteristics_i_advances', models.IntegerField(default='0', verbose_name='i_advances')),
                ('characteristics_ag_advances', models.IntegerField(default='0', verbose_name='ag_advances')),
                ('characteristics_dex_advances', models.IntegerField(default='0', verbose_name='dex_advances')),
                ('characteristics_int_advances', models.IntegerField(default='0', verbose_name='int_advances')),
                ('characteristics_wp_advances', models.IntegerField(default='0', verbose_name='wp_advances')),
                ('characteristics_fel_advances', models.IntegerField(default='0', verbose_name='fel_advances')),
                ('fate_fate', models.IntegerField(default='0', verbose_name='fate_fate')),
                ('fate_fortune', models.IntegerField(default='0', verbose_name='fate_fortune')),
                ('resilience_resilience', models.IntegerField(default='0', verbose_name='resilience_resilience')),
                ('resilience_resolve', models.IntegerField(default='0', verbose_name='resilience_resolve')),
                ('resilience_motivation', models.IntegerField(default='0', verbose_name='resilience_motivation')),
                ('experience_current', models.IntegerField(default='0', verbose_name='experience_current')),
                ('experience_spent', models.IntegerField(default='0', verbose_name='experience_spent')),
                ('experience_total', models.IntegerField(default='0', verbose_name='experience_total')),
                ('movement_movement', models.IntegerField(default='0', verbose_name='movement_movement')),
                ('movement_walk', models.IntegerField(default='0', verbose_name='movement_walk')),
                ('movement_run', models.IntegerField(default='0', verbose_name='movement_run')),
                ('ambitions_shortterm', models.TextField(default='', verbose_name='Shortterm')),
                ('ambitions_longterm', models.TextField(default='', verbose_name='Longterm')),
                ('career_path', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='WarhammerFantasyRoleplayVirtualGM_app.careerpath', verbose_name='CareerPath')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Eyes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Hair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Skils',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('characteristics', models.CharField(default='', max_length=3)),
                ('description', models.TextField(default='', verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Talent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(default='', verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Player')),
            ],
        ),
        migrations.CreateModel(
            name='Character2Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adv', models.IntegerField(default='0', verbose_name='adv')),
                ('characters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WarhammerFantasyRoleplayVirtualGM_app.character')),
                ('skills', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WarhammerFantasyRoleplayVirtualGM_app.skils')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='ch_class',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='WarhammerFantasyRoleplayVirtualGM_app.characterclass', verbose_name='Class'),
        ),
        migrations.AddField(
            model_name='character',
            name='eyes',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='WarhammerFantasyRoleplayVirtualGM_app.eyes', verbose_name='Eyes'),
        ),
        migrations.AddField(
            model_name='character',
            name='hair',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='WarhammerFantasyRoleplayVirtualGM_app.hair', verbose_name='Hair'),
        ),
        migrations.AddField(
            model_name='character',
            name='player',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='WarhammerFantasyRoleplayVirtualGM_app.player', verbose_name='Player'),
        ),
        migrations.AddField(
            model_name='character',
            name='species',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='WarhammerFantasyRoleplayVirtualGM_app.species', verbose_name='Species'),
        ),
        migrations.AddField(
            model_name='character',
            name='status',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='WarhammerFantasyRoleplayVirtualGM_app.status', verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='Campaign2Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WarhammerFantasyRoleplayVirtualGM_app.campaign')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WarhammerFantasyRoleplayVirtualGM_app.player')),
            ],
        ),
    ]
