# Generated by Django 3.2.19 on 2023-08-05 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WarhammerFantasyRoleplayVirtualGM_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='random_interal_end',
            field=models.IntegerField(default=0, verbose_name='random_interal_start'),
        ),
        migrations.AddField(
            model_name='species',
            name='random_interal_start',
            field=models.IntegerField(default=0, verbose_name='random_interal_start'),
        ),
    ]
