# Generated by Django 3.2.19 on 2023-08-27 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WarhammerFantasyRoleplayVirtualGM_app', '0002_classtrappings'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classtrappings',
            unique_together={('ch_class', 'trapping')},
        ),
    ]
