# Generated by Django 3.2.19 on 2023-07-25 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WarhammerFantasyRoleplayVirtualGM_app', '0003_auto_20230724_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skils',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='experience_current',
            field=models.IntegerField(default='0', verbose_name='experience_current'),
        ),
        migrations.AddField(
            model_name='character',
            name='experience_spent',
            field=models.IntegerField(default='0', verbose_name='experience_spent'),
        ),
        migrations.AddField(
            model_name='character',
            name='experience_total',
            field=models.IntegerField(default='0', verbose_name='experience_total'),
        ),
        migrations.AddField(
            model_name='character',
            name='fate_fate',
            field=models.IntegerField(default='0', verbose_name='fate_fate'),
        ),
        migrations.AddField(
            model_name='character',
            name='fate_fortune',
            field=models.IntegerField(default='0', verbose_name='fate_fortune'),
        ),
        migrations.AddField(
            model_name='character',
            name='movement_movement',
            field=models.IntegerField(default='0', verbose_name='movement_movement'),
        ),
        migrations.AddField(
            model_name='character',
            name='movement_run',
            field=models.IntegerField(default='0', verbose_name='movement_run'),
        ),
        migrations.AddField(
            model_name='character',
            name='movement_walk',
            field=models.IntegerField(default='0', verbose_name='movement_walk'),
        ),
        migrations.AddField(
            model_name='character',
            name='resilience_motivation',
            field=models.IntegerField(default='0', verbose_name='resilience_motivation'),
        ),
        migrations.AddField(
            model_name='character',
            name='resilience_resilience',
            field=models.IntegerField(default='0', verbose_name='resilience_resilience'),
        ),
        migrations.AddField(
            model_name='character',
            name='resilience_resolve',
            field=models.IntegerField(default='0', verbose_name='resilience_resolve'),
        ),
        migrations.CreateModel(
            name='Character2Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adv', models.IntegerField(default='0', verbose_name='adv')),
                ('characters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WarhammerFantasyRoleplayVirtualGM_app.character')),
                ('skills', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WarhammerFantasyRoleplayVirtualGM_app.skils')),
            ],
        ),
    ]
