# Generated by Django 3.2.19 on 2023-08-05 17:08

import WarhammerFantasyRoleplayVirtualGM_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WarhammerFantasyRoleplayVirtualGM_app', '0003_examplename'),
    ]

    operations = [
        migrations.AddField(
            model_name='examplename',
            name='sex',
            field=models.CharField(default='f', max_length=1, validators=[WarhammerFantasyRoleplayVirtualGM_app.validators.validator_sex]),
        ),
    ]
