# Generated by Django 3.2.19 on 2023-08-27 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WarhammerFantasyRoleplayVirtualGM_app', '0003_alter_classtrappings_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='trappings',
            field=models.ManyToManyField(to='WarhammerFantasyRoleplayVirtualGM_app.Trapping'),
        ),
    ]
