# Generated by Django 3.2.19 on 2023-07-25 15:46

from django.db import migrations, models

from WarhammerFantasyRoleplayVirtualGM_app.models import Skils


def copy_data(apps, schema_editor):
    data = [
        ["Art", "Dex"],
        ["Gossip", "Fel"],
        ["Athletics", "Ag"],
        ["Haggle", "Fel"],
        ["Bribery", "Fel"],
        ["Intimidate", "S"],
        ["Charm", "Fel"],
        ["Intuition", "I"],
        ["Charm Animal", "WP"],
        ["Leadership", "Fel"],
        ["Climb", "S"],
        ["Melee (Basic)", "WS"],
        ["Cool", "WP"],
        ["Melee", "WS"],
        ["Consume Alcohol", "T"],
        ["Navigation", "I"],
        ["Dodge", "Ag"],
        ["Outdoor Survival", "Int"],
        ["Drive", "Ag"],
        ["Perception", "I"],
        ["Endurance", "T"],
        ["Ride", "Ag"],
        ["Entertain", "Fel"],
        ["Row", "S"],
        ["Gamble", "Int"],
        ["Stealth", "Ag"]
    ]
    for name, char in data:
        skill = Skils(name=name, characteristics=char)
        skill.save()


class Migration(migrations.Migration):

    dependencies = [
        ('WarhammerFantasyRoleplayVirtualGM_app', '0004_auto_20230725_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='skils',
            name='characteristics',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.RunPython(copy_data),
    ]
