# Generated by Django 3.2.19 on 2023-08-27 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WarhammerFantasyRoleplayVirtualGM_app', '0004_character_trappings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='trappings',
        ),
        migrations.CreateModel(
            name='Character2Trappingl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enc', models.IntegerField(default='0', verbose_name='enc')),
                ('characters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WarhammerFantasyRoleplayVirtualGM_app.character')),
                ('trapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WarhammerFantasyRoleplayVirtualGM_app.trapping')),
            ],
            options={
                'unique_together': {('characters', 'trapping')},
            },
        ),
    ]
