# Generated by Django 3.2.19 on 2023-08-05 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WarhammerFantasyRoleplayVirtualGM_app', '0004_examplename_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='career_path',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='WarhammerFantasyRoleplayVirtualGM_app.careerpath', verbose_name='CareerPath'),
        ),
        migrations.AlterField(
            model_name='character',
            name='eyes',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='WarhammerFantasyRoleplayVirtualGM_app.eyes', verbose_name='Eyes'),
        ),
        migrations.AlterField(
            model_name='character',
            name='hair',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='WarhammerFantasyRoleplayVirtualGM_app.hair', verbose_name='Hair'),
        ),
        migrations.AlterField(
            model_name='character',
            name='status',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='WarhammerFantasyRoleplayVirtualGM_app.status', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='examplename',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
