# Generated by Django 3.2.19 on 2023-08-28 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WarhammerFantasyRoleplayVirtualGM_app', '0005_auto_20230827_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='character2talent',
            name='is_career_skill',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='character2talent',
            name='is_species_skill',
            field=models.BooleanField(default=False),
        ),
    ]
