# Generated by Django 3.2.19 on 2023-08-05 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WarhammerFantasyRoleplayVirtualGM_app', '0005_auto_20230805_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='species',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='WarhammerFantasyRoleplayVirtualGM_app.species', verbose_name='Species'),
        ),
    ]
