# Generated by Django 3.2.19 on 2023-07-25 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WarhammerFantasyRoleplayVirtualGM_app', '0005_skils_characteristics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(default='', verbose_name='Description')),
            ],
        ),
        migrations.AddField(
            model_name='skils',
            name='description',
            field=models.TextField(default='', verbose_name='Description'),
        ),
    ]
