# Generated by Django 3.2.19 on 2023-08-05 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WarhammerFantasyRoleplayVirtualGM_app', '0006_alter_character_species'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='career_path',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WarhammerFantasyRoleplayVirtualGM_app.careerpath', verbose_name='CareerPath'),
        ),
        migrations.AlterField(
            model_name='character',
            name='ch_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WarhammerFantasyRoleplayVirtualGM_app.characterclass', verbose_name='Class'),
        ),
        migrations.AlterField(
            model_name='character',
            name='eyes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WarhammerFantasyRoleplayVirtualGM_app.eyes', verbose_name='Eyes'),
        ),
        migrations.AlterField(
            model_name='character',
            name='hair',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WarhammerFantasyRoleplayVirtualGM_app.hair', verbose_name='Hair'),
        ),
        migrations.AlterField(
            model_name='character',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WarhammerFantasyRoleplayVirtualGM_app.player', verbose_name='Player'),
        ),
        migrations.AlterField(
            model_name='character',
            name='species',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WarhammerFantasyRoleplayVirtualGM_app.species', verbose_name='Species'),
        ),
        migrations.AlterField(
            model_name='character',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WarhammerFantasyRoleplayVirtualGM_app.status', verbose_name='Status'),
        ),
    ]
