# Generated by Django 3.2.19 on 2023-07-25 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WarhammerFantasyRoleplayVirtualGM_app', '0006_auto_20230725_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='ambitions_longterm',
            field=models.TextField(default='', verbose_name='Longterm'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='ambitions_shortterm',
            field=models.TextField(default='', verbose_name='Shortterm'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='party_name',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='character',
            name='ambitions_longterm',
            field=models.TextField(default='', verbose_name='Longterm'),
        ),
        migrations.AddField(
            model_name='character',
            name='ambitions_shortterm',
            field=models.TextField(default='', verbose_name='Shortterm'),
        ),
    ]
