# Generated by Django 3.2.19 on 2023-07-26 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WarhammerFantasyRoleplayVirtualGM_app', '0007_auto_20230725_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='characters',
        ),
    ]
