# Generated by Django 3.2.19 on 2023-07-26 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WarhammerFantasyRoleplayVirtualGM_app', '0008_remove_campaign_characters'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='players',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WarhammerFantasyRoleplayVirtualGM_app.player'),
        ),
    ]
