# Generated by Django 3.2.19 on 2023-08-28 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WarhammerFantasyRoleplayVirtualGM_app', '0008_auto_20230828_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='name',
        ),
        migrations.AddField(
            model_name='careerpath',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WarhammerFantasyRoleplayVirtualGM_app.status', verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='status',
            name='level',
            field=models.IntegerField(default='0', verbose_name='Status Level'),
        ),
        migrations.AddField(
            model_name='status',
            name='tier',
            field=models.CharField(choices=[('N', 'NONE'), ('B', 'Brass'), ('S', 'Silver'), ('G', 'Gold')], default='N', max_length=1, verbose_name='Tier'),
        ),
    ]
