# Generated by Django 3.2.19 on 2023-07-26 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WarhammerFantasyRoleplayVirtualGM_app', '0009_campaign_players'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='players',
        ),
        migrations.AddField(
            model_name='player',
            name='campaign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WarhammerFantasyRoleplayVirtualGM_app.campaign', verbose_name='Campaign'),
        ),
    ]
