# Generated by Django 3.2.19 on 2023-08-08 17:08

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('WarhammerFantasyRoleplayVirtualGM_app', '0009_class_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='career',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WarhammerFantasyRoleplayVirtualGM_app.career', verbose_name='Career'),
        ),
        migrations.AlterField(
            model_name='character',
            name='ch_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WarhammerFantasyRoleplayVirtualGM_app.class', verbose_name='Career'),
        ),
    ]
