# Generated by Django 3.2.19 on 2023-08-08 18:17

from django.db import migrations, models
import django.db.models.deletion


from WarhammerFantasyRoleplayVirtualGM_app.models import Class
from WarhammerFantasyRoleplayVirtualGM_app.models import Career


def add_Class_Career(apps, schema_editor):
    data = [
        "ACADEMICS",
        "BURGHERS",
        "COURTIERS",
        "PEASANTS",
        "RANGERS",
        "RIVERFOLK",
        "ROGUES",
        "WARRIORS"
    ]

    for title in data:
        refBook = Class(name = title)
        refBook.save()

    data = [
            {'Class': 'ACADEMICS', 'Career': 'Apothecary', 'Human_Start': '1', 'Human_End': '1', 'Dwarf_Start': '1', 'Dwarf_End': '1', 'Halfling_Start': '1', 'Halfling_End': '1', 'High_Elf_Start': '1', 'High_Elf_End': '2', 'Wood_Elf_Start': '0', 'Wood_Elf_End': '0'}
            ,
            {'Class': 'ACADEMICS', 'Career': 'Engineer', 'Human_Start': '2', 'Human_End': '2', 'Dwarf_Start': '2', 'Dwarf_End': '4', 'Halfling_Start': '2', 'Halfling_End': '2', 'High_Elf_Start': '0', 'High_Elf_End': '0', 'Wood_Elf_Start': '0', 'Wood_Elf_End': '0'}
            ,
            {'Class': 'ACADEMICS', 'Career': 'Lawyer', 'Human_Start': '3', 'Human_End': '3', 'Dwarf_Start': '5', 'Dwarf_End': '6', 'Halfling_Start': '3', 'Halfling_End': '4', 'High_Elf_Start': '3', 'High_Elf_End': '6', 'Wood_Elf_Start': '0', 'Wood_Elf_End': '0'}
            ,
            {'Class': 'ACADEMICS', 'Career': 'Nun', 'Human_Start': '4', 'Human_End': '4', 'Dwarf_Start': '0', 'Dwarf_End': '0', 'Halfling_Start': '0', 'Halfling_End': '0', 'High_Elf_Start': '0', 'High_Elf_End': '0', 'Wood_Elf_Start': '0', 'Wood_Elf_End': '0'}
            ,
            {'Class': 'ACADEMICS', 'Career': 'Physician', 'Human_Start': '6', 'Human_End': '6', 'Dwarf_Start': '7', 'Dwarf_End': '7', 'Halfling_Start': '5', 'Halfling_End': '6', 'High_Elf_Start': '7', 'High_Elf_End': '8', 'Wood_Elf_Start': '0', 'Wood_Elf_End': '0'}
            ,
            {'Class': 'ACADEMICS', 'Career': 'Priest', 'Human_Start': '7', 'Human_End': '11', 'Dwarf_Start': '0', 'Dwarf_End': '0', 'Halfling_Start': '0', 'Halfling_End': '0', 'High_Elf_Start': '0', 'High_Elf_End': '0', 'Wood_Elf_Start': '0', 'Wood_Elf_End': '0'}
            ,
            {'Class': 'ACADEMICS', 'Career': 'Scholar', 'Human_Start': '12', 'Human_End': '13', 'Dwarf_Start': '8', 'Dwarf_End': '9', 'Halfling_Start': '7', 'Halfling_End': '8', 'High_Elf_Start': '9', 'High_Elf_End': '12', 'Wood_Elf_Start': '1', 'Wood_Elf_End': '1'}
            ,
            {'Class': 'ACADEMICS', 'Career': 'Wizard', 'Human_Start': '14', 'Human_End': '14', 'Dwarf_Start': '0', 'Dwarf_End': '0', 'Halfling_Start': '0', 'Halfling_End': '0', 'High_Elf_Start': '13', 'High_Elf_End': '16', 'Wood_Elf_Start': '2', 'Wood_Elf_End': '5'}
            ,
            {'Class': 'BURGHERS', 'Career': 'Agitator', 'Human_Start': '15', 'Human_End': '15', 'Dwarf_Start': '10', 'Dwarf_End': '11', 'Halfling_Start': '9', 'Halfling_End': '10', 'High_Elf_Start': '0', 'High_Elf_End': '0', 'Wood_Elf_Start': '0', 'Wood_Elf_End': '0'}
            ,
            {'Class': 'BURGHERS', 'Career': 'Artisan', 'Human_Start': '16', 'Human_End': '17', 'Dwarf_Start': '12', 'Dwarf_End': '17', 'Halfling_Start': '11', 'Halfling_End': '15', 'High_Elf_Start': '17', 'High_Elf_End': '19', 'Wood_Elf_Start': '6', 'Wood_Elf_End': '10'}
            ,
            {'Class': 'BURGHERS', 'Career': 'Beggar', 'Human_Start': '18', 'Human_End': '19', 'Dwarf_Start': '18', 'Dwarf_End': '18', 'Halfling_Start': '16', 'Halfling_End': '19', 'High_Elf_Start': '0', 'High_Elf_End': '0', 'Wood_Elf_Start': '0', 'Wood_Elf_End': '0'}
            ,
            {'Class': 'BURGHERS', 'Career': 'Investigator', 'Human_Start': '20', 'Human_End': '20', 'Dwarf_Start': '19', 'Dwarf_End': '20', 'Halfling_Start': '20', 'Halfling_End': '21', 'High_Elf_Start': '20', 'High_Elf_End': '21', 'Wood_Elf_Start': '0', 'Wood_Elf_End': '0'}
            ,
            {'Class': 'BURGHERS', 'Career': 'Merchant', 'Human_Start': '21', 'Human_End': '21', 'Dwarf_Start': '21', 'Dwarf_End': '24', 'Halfling_Start': '22', 'Halfling_End': '25', 'High_Elf_Start': '22', 'High_Elf_End': '26', 'Wood_Elf_Start': '0', 'Wood_Elf_End': '0'}
            ,
            {'Class': 'BURGHERS', 'Career': 'Rat Catcher', 'Human_Start': '22', 'Human_End': '23', 'Dwarf_Start': '25', 'Dwarf_End': '25', 'Halfling_Start': '26', 'Halfling_End': '28', 'High_Elf_Start': '0', 'High_Elf_End': '0', 'Wood_Elf_Start': '0', 'Wood_Elf_End': '0'}
            ,
            {'Class': 'BURGHERS', 'Career': 'Townsman', 'Human_Start': '24', 'Human_End': '26', 'Dwarf_Start': '26', 'Dwarf_End': '31', 'Halfling_Start': '29', 'Halfling_End': '31', 'High_Elf_Start': '27', 'High_Elf_End': '28', 'Wood_Elf_Start': '0', 'Wood_Elf_End': '0'}
            ,
            {'Class': 'BURGHERS', 'Career': 'Watchman', 'Human_Start': '27', 'Human_End': '27', 'Dwarf_Start': '32', 'Dwarf_End': '34', 'Halfling_Start': '32', 'Halfling_End': '33', 'High_Elf_Start': '29', 'High_Elf_End': '29', 'Wood_Elf_Start': '0', 'Wood_Elf_End': '0'}
            ,
            {'Class': 'COURTIERS', 'Career': 'Advisor', 'Human_Start': '28', 'Human_End': '28', 'Dwarf_Start': '35', 'Dwarf_End': '36', 'Halfling_Start': '34', 'Halfling_End': '34', 'High_Elf_Start': '30', 'High_Elf_End': '31', 'Wood_Elf_Start': '11', 'Wood_Elf_End': '14'}
            ,
            {'Class': 'COURTIERS', 'Career': 'Artist', 'Human_Start': '29', 'Human_End': '29', 'Dwarf_Start': '37', 'Dwarf_End': '37', 'Halfling_Start': '35', 'Halfling_End': '36', 'High_Elf_Start': '32', 'High_Elf_End': '32', 'Wood_Elf_Start': '15', 'Wood_Elf_End': '18'}
            ,
            {'Class': 'COURTIERS', 'Career': 'Duellist', 'Human_Start': '30', 'Human_End': '30', 'Dwarf_Start': '38', 'Dwarf_End': '38', 'Halfling_Start': '0', 'Halfling_End': '0', 'High_Elf_Start': '33', 'High_Elf_End': '34', 'Wood_Elf_Start': '0', 'Wood_Elf_End': '0'}
            ,
            {'Class': 'COURTIERS', 'Career': 'Envoy', 'Human_Start': '31', 'Human_End': '31', 'Dwarf_Start': '39', 'Dwarf_End': '40', 'Halfling_Start': '37', 'Halfling_End': '37', 'High_Elf_Start': '35', 'High_Elf_End': '37', 'Wood_Elf_Start': '19', 'Wood_Elf_End': '25'}
            ,
            {'Class': 'COURTIERS', 'Career': 'Noble', 'Human_Start': '32', 'Human_End': '32', 'Dwarf_Start': '41', 'Dwarf_End': '41', 'Halfling_Start': '0', 'Halfling_End': '0', 'High_Elf_Start': '38', 'High_Elf_End': '40', 'Wood_Elf_Start': '26', 'Wood_Elf_End': '31'}
            ,
            {'Class': 'COURTIERS', 'Career': 'Servant', 'Human_Start': '33', 'Human_End': '35', 'Dwarf_Start': '42', 'Dwarf_End': '42', 'Halfling_Start': '38', 'Halfling_End': '43', 'High_Elf_Start': '0', 'High_Elf_End': '0', 'Wood_Elf_Start': '0', 'Wood_Elf_End': '0'}
            ,
            {'Class': 'COURTIERS', 'Career': 'Spy', 'Human_Start': '36', 'Human_End': '36', 'Dwarf_Start': '43', 'Dwarf_End': '43', 'Halfling_Start': '44', 'Halfling_End': '44', 'High_Elf_Start': '41', 'High_Elf_End': '43', 'Wood_Elf_Start': '32', 'Wood_Elf_End': '35'}
            ,
            {'Class': 'COURTIERS', 'Career': 'Warden', 'Human_Start': '37', 'Human_End': '37', 'Dwarf_Start': '44', 'Dwarf_End': '45', 'Halfling_Start': '45', 'Halfling_End': '46', 'High_Elf_Start': '44', 'High_Elf_End': '45', 'Wood_Elf_Start': '0', 'Wood_Elf_End': '0'}
            ,
            {'Class': 'PEASANTS', 'Career': 'Bailiff', 'Human_Start': '38', 'Human_End': '38', 'Dwarf_Start': '46', 'Dwarf_End': '47', 'Halfling_Start': '47', 'Halfling_End': '47', 'High_Elf_Start': '0', 'High_Elf_End': '0', 'Wood_Elf_Start': '0', 'Wood_Elf_End': '0'}
            ,
            {'Class': 'PEASANTS', 'Career': 'Hedge Witch', 'Human_Start': '39', 'Human_End': '39', 'Dwarf_Start': '0', 'Dwarf_End': '0', 'Halfling_Start': '0', 'Halfling_End': '0', 'High_Elf_Start': '0', 'High_Elf_End': '0', 'Wood_Elf_Start': '0', 'Wood_Elf_End': '0'}
            ,
            {'Class': 'PEASANTS', 'Career': 'Herbalist', 'Human_Start': '40', 'Human_End': '40', 'Dwarf_Start': '0', 'Dwarf_End': '0', 'Halfling_Start': '48', 'Halfling_End': '50', 'High_Elf_Start': '46', 'High_Elf_End': '47', 'Wood_Elf_Start': '36', 'Wood_Elf_End': '42'}
            ,
            {'Class': 'PEASANTS', 'Career': 'Hunter', 'Human_Start': '41', 'Human_End': '42', 'Dwarf_Start': '48', 'Dwarf_End': '49', 'Halfling_Start': '51', 'Halfling_End': '52', 'High_Elf_Start': '48', 'High_Elf_End': '50', 'Wood_Elf_Start': '43', 'Wood_Elf_End': '52'}
            ,
            {'Class': 'PEASANTS', 'Career': 'Miner', 'Human_Start': '43', 'Human_End': '43', 'Dwarf_Start': '50', 'Dwarf_End': '54', 'Halfling_Start': '53', 'Halfling_End': '53', 'High_Elf_Start': '0', 'High_Elf_End': '0', 'Wood_Elf_Start': '0', 'Wood_Elf_End': '0'}
            ,
            {'Class': 'PEASANTS', 'Career': 'Mystic', 'Human_Start': '44', 'Human_End': '44', 'Dwarf_Start': '0', 'Dwarf_End': '0', 'Halfling_Start': '0', 'Halfling_End': '0', 'High_Elf_Start': '0', 'High_Elf_End': '0', 'Wood_Elf_Start': '53', 'Wood_Elf_End': '57'}
            ,
            {'Class': 'PEASANTS', 'Career': 'Scout', 'Human_Start': '45', 'Human_End': '45', 'Dwarf_Start': '55', 'Dwarf_End': '55', 'Halfling_Start': '54', 'Halfling_End': '54', 'High_Elf_Start': '51', 'High_Elf_End': '56', 'Wood_Elf_Start': '58', 'Wood_Elf_End': '68'}
            ,
            {'Class': 'PEASANTS', 'Career': 'Villager', 'Human_Start': '46', 'Human_End': '50', 'Dwarf_Start': '56', 'Dwarf_End': '56', 'Halfling_Start': '55', 'Halfling_End': '57', 'High_Elf_Start': '0', 'High_Elf_End': '0', 'Wood_Elf_Start': '0', 'Wood_Elf_End': '0'}
            ,
            {'Class': 'RANGERS', 'Career': 'Bounty Hunter', 'Human_Start': '51', 'Human_End': '51', 'Dwarf_Start': '57', 'Dwarf_End': '60', 'Halfling_Start': '58', 'Halfling_End': '58', 'High_Elf_Start': '57', 'High_Elf_End': '59', 'Wood_Elf_Start': '69', 'Wood_Elf_End': '70'}
            ,
            {'Class': 'RANGERS', 'Career': 'Coachman', 'Human_Start': '52', 'Human_End': '52', 'Dwarf_Start': '61', 'Dwarf_End': '61', 'Halfling_Start': '59', 'Halfling_End': '60', 'High_Elf_Start': '0', 'High_Elf_End': '0', 'Wood_Elf_Start': '0', 'Wood_Elf_End': '0'}
            ,
            {'Class': 'RANGERS', 'Career': 'Entertainer', 'Human_Start': '53', 'Human_End': '54', 'Dwarf_Start': '62', 'Dwarf_End': '63', 'Halfling_Start': '61', 'Halfling_End': '63', 'High_Elf_Start': '60', 'High_Elf_End': '62', 'Wood_Elf_Start': '71', 'Wood_Elf_End': '75'}
            ,
            {'Class': 'RANGERS', 'Career': 'Flagellant', 'Human_Start': '55', 'Human_End': '56', 'Dwarf_Start': '0', 'Dwarf_End': '0', 'Halfling_Start': '0', 'Halfling_End': '0', 'High_Elf_Start': '0', 'High_Elf_End': '0', 'Wood_Elf_Start': '0', 'Wood_Elf_End': '0'}
            ,
            {'Class': 'RANGERS', 'Career': 'Messenger', 'Human_Start': '57', 'Human_End': '57', 'Dwarf_Start': '64', 'Dwarf_End': '65', 'Halfling_Start': '64', 'Halfling_End': '65', 'High_Elf_Start': '63', 'High_Elf_End': '63', 'Wood_Elf_Start': '76', 'Wood_Elf_End': '78'}
            ,
            {'Class': 'RANGERS', 'Career': 'Pedlar', 'Human_Start': '58', 'Human_End': '58', 'Dwarf_Start': '66', 'Dwarf_End': '67', 'Halfling_Start': '66', 'Halfling_End': '67', 'High_Elf_Start': '0', 'High_Elf_End': '0', 'Wood_Elf_Start': '0', 'Wood_Elf_End': '0'}
            ,
            {'Class': 'RANGERS', 'Career': 'Road Warden', 'Human_Start': '59', 'Human_End': '59', 'Dwarf_Start': '0', 'Dwarf_End': '0', 'Halfling_Start': '68', 'Halfling_End': '68', 'High_Elf_Start': '0', 'High_Elf_End': '0', 'Wood_Elf_Start': '0', 'Wood_Elf_End': '0'}
            ,
            {'Class': 'RANGERS', 'Career': 'Witch Hunter', 'Human_Start': '60', 'Human_End': '60', 'Dwarf_Start': '0', 'Dwarf_End': '0', 'Halfling_Start': '0', 'Halfling_End': '0', 'High_Elf_Start': '0', 'High_Elf_End': '0', 'Wood_Elf_Start': '0', 'Wood_Elf_End': '0'}
            ,
            {'Class': 'RIVERFOLK', 'Career': 'Boatman', 'Human_Start': '61', 'Human_End': '62', 'Dwarf_Start': '68', 'Dwarf_End': '69', 'Halfling_Start': '69', 'Halfling_End': '69', 'High_Elf_Start': '64', 'High_Elf_End': '64', 'Wood_Elf_Start': '0', 'Wood_Elf_End': '0'}
            ,
            {'Class': 'RIVERFOLK', 'Career': 'Huffer', 'Human_Start': '63', 'Human_End': '63', 'Dwarf_Start': '70', 'Dwarf_End': '70', 'Halfling_Start': '70', 'Halfling_End': '70', 'High_Elf_Start': '0', 'High_Elf_End': '0', 'Wood_Elf_Start': '0', 'Wood_Elf_End': '0'}
            ,
            {'Class': 'RIVERFOLK', 'Career': 'Riverwarden', 'Human_Start': '64', 'Human_End': '65', 'Dwarf_Start': '0', 'Dwarf_End': '0', 'Halfling_Start': '71', 'Halfling_End': '71', 'High_Elf_Start': '0', 'High_Elf_End': '0', 'Wood_Elf_Start': '0', 'Wood_Elf_End': '0'}
            ,
            {'Class': 'RIVERFOLK', 'Career': 'Riverwoman', 'Human_Start': '66', 'Human_End': '68', 'Dwarf_Start': '71', 'Dwarf_End': '72', 'Halfling_Start': '72', 'Halfling_End': '74', 'High_Elf_Start': '0', 'High_Elf_End': '0', 'Wood_Elf_Start': '0', 'Wood_Elf_End': '0'}
            ,
            {'Class': 'RIVERFOLK', 'Career': 'Seaman', 'Human_Start': '69', 'Human_End': '70', 'Dwarf_Start': '73', 'Dwarf_End': '73', 'Halfling_Start': '75', 'Halfling_End': '75', 'High_Elf_Start': '65', 'High_Elf_End': '79', 'Wood_Elf_Start': '0', 'Wood_Elf_End': '0'}
            ,
            {'Class': 'RIVERFOLK', 'Career': 'Smuggler', 'Human_Start': '71', 'Human_End': '71', 'Dwarf_Start': '74', 'Dwarf_End': '75', 'Halfling_Start': '76', 'Halfling_End': '79', 'High_Elf_Start': '80', 'High_Elf_End': '80', 'Wood_Elf_Start': '0', 'Wood_Elf_End': '0'}
            ,
            {'Class': 'RIVERFOLK', 'Career': 'Stevedore', 'Human_Start': '72', 'Human_End': '73', 'Dwarf_Start': '76', 'Dwarf_End': '77', 'Halfling_Start': '80', 'Halfling_End': '82', 'High_Elf_Start': '0', 'High_Elf_End': '0', 'Wood_Elf_Start': '0', 'Wood_Elf_End': '0'}
            ,
            {'Class': 'RIVERFOLK', 'Career': 'Wrecker', 'Human_Start': '74', 'Human_End': '74', 'Dwarf_Start': '78', 'Dwarf_End': '78', 'Halfling_Start': '0', 'Halfling_End': '0', 'High_Elf_Start': '0', 'High_Elf_End': '0', 'Wood_Elf_Start': '79', 'Wood_Elf_End': '79'}
            ,
            {'Class': 'ROGUES', 'Career': 'Bawd', 'Human_Start': '75', 'Human_End': '76', 'Dwarf_Start': '0', 'Dwarf_End': '0', 'Halfling_Start': '83', 'Halfling_End': '85', 'High_Elf_Start': '81', 'High_Elf_End': '82', 'Wood_Elf_Start': '0', 'Wood_Elf_End': '0'}
            ,
            {'Class': 'ROGUES', 'Career': 'Charlatan', 'Human_Start': '77', 'Human_End': '77', 'Dwarf_Start': '0', 'Dwarf_End': '0', 'Halfling_Start': '86', 'Halfling_End': '86', 'High_Elf_Start': '83', 'High_Elf_End': '85', 'Wood_Elf_Start': '0', 'Wood_Elf_End': '0'}
            ,
            {'Class': 'ROGUES', 'Career': 'Fence', 'Human_Start': '78', 'Human_End': '78', 'Dwarf_Start': '79', 'Dwarf_End': '79', 'Halfling_Start': '87', 'Halfling_End': '87', 'High_Elf_Start': '0', 'High_Elf_End': '0', 'Wood_Elf_Start': '0', 'Wood_Elf_End': '0'}
            ,
            {'Class': 'ROGUES', 'Career': 'Grave Robber', 'Human_Start': '79', 'Human_End': '79', 'Dwarf_Start': '0', 'Dwarf_End': '0', 'Halfling_Start': '88', 'Halfling_End': '88', 'High_Elf_Start': '0', 'High_Elf_End': '0', 'Wood_Elf_Start': '0', 'Wood_Elf_End': '0'}
            ,
            {'Class': 'ROGUES', 'Career': 'Outlaw', 'Human_Start': '80', 'Human_End': '83', 'Dwarf_Start': '80', 'Dwarf_End': '82', 'Halfling_Start': '89', 'Halfling_End': '89', 'High_Elf_Start': '86', 'High_Elf_End': '88', 'Wood_Elf_Start': '80', 'Wood_Elf_End': '85'}
            ,
            {'Class': 'ROGUES', 'Career': 'Racketeer', 'Human_Start': '84', 'Human_End': '84', 'Dwarf_Start': '83', 'Dwarf_End': '83', 'Halfling_Start': '90', 'Halfling_End': '90', 'High_Elf_Start': '0', 'High_Elf_End': '0', 'Wood_Elf_Start': '0', 'Wood_Elf_End': '0'}
            ,
            {'Class': 'ROGUES', 'Career': 'Thief', 'Human_Start': '85', 'Human_End': '87', 'Dwarf_Start': '84', 'Dwarf_End': '84', 'Halfling_Start': '91', 'Halfling_End': '94', 'High_Elf_Start': '0', 'High_Elf_End': '0', 'Wood_Elf_Start': '0', 'Wood_Elf_End': '0'}
            ,
            {'Class': 'ROGUES', 'Career': 'Witch', 'Human_Start': '88', 'Human_End': '88', 'Dwarf_Start': '0', 'Dwarf_End': '0', 'Halfling_Start': '0', 'Halfling_End': '0', 'High_Elf_Start': '0', 'High_Elf_End': '0', 'Wood_Elf_Start': '0', 'Wood_Elf_End': '0'}
            ,
            {'Class': 'WARRIORS', 'Career': 'Cavalryman', 'Human_Start': '89', 'Human_End': '90', 'Dwarf_Start': '0', 'Dwarf_End': '0', 'Halfling_Start': '0', 'Halfling_End': '0', 'High_Elf_Start': '89', 'High_Elf_End': '92', 'Wood_Elf_Start': '86', 'Wood_Elf_End': '90'}
            ,
            {'Class': 'WARRIORS', 'Career': 'Guard', 'Human_Start': '91', 'Human_End': '92', 'Dwarf_Start': '85', 'Dwarf_End': '87', 'Halfling_Start': '95', 'Halfling_End': '96', 'High_Elf_Start': '93', 'High_Elf_End': '94', 'Wood_Elf_Start': '91', 'Wood_Elf_End': '92'}
            ,
            {'Class': 'WARRIORS', 'Career': 'Knight', 'Human_Start': '93', 'Human_End': '93', 'Dwarf_Start': '0', 'Dwarf_End': '0', 'Halfling_Start': '0', 'Halfling_End': '0', 'High_Elf_Start': '95', 'High_Elf_End': '95', 'Wood_Elf_Start': '93', 'Wood_Elf_End': '94'}
            ,
            {'Class': 'WARRIORS', 'Career': 'Pit Fighter', 'Human_Start': '94', 'Human_End': '94', 'Dwarf_Start': '88', 'Dwarf_End': '90', 'Halfling_Start': '97', 'Halfling_End': '97', 'High_Elf_Start': '96', 'High_Elf_End': '97', 'Wood_Elf_Start': '95', 'Wood_Elf_End': '96'}
            ,
            {'Class': 'WARRIORS', 'Career': 'Protagonist', 'Human_Start': '95', 'Human_End': '95', 'Dwarf_Start': '91', 'Dwarf_End': '93', 'Halfling_Start': '0', 'Halfling_End': '0', 'High_Elf_Start': '98', 'High_Elf_End': '98', 'Wood_Elf_Start': '0', 'Wood_Elf_End': '0'}
            ,
            {'Class': 'WARRIORS', 'Career': 'Soldier', 'Human_Start': '96', 'Human_End': '99', 'Dwarf_Start': '94', 'Dwarf_End': '96', 'Halfling_Start': '98', 'Halfling_End': '100', 'High_Elf_Start': '99', 'High_Elf_End': '100', 'Wood_Elf_Start': '97', 'Wood_Elf_End': '100'}
            ,
            {'Class': 'WARRIORS', 'Career': 'Slayer', 'Human_Start': '0', 'Human_End': '0', 'Dwarf_Start': '97', 'Dwarf_End': '100', 'Halfling_Start': '0', 'Halfling_End': '0', 'High_Elf_Start': '0', 'High_Elf_End': '0', 'Wood_Elf_Start': '0', 'Wood_Elf_End': '0'}
            ,
            {'Class': 'WARRIORS', 'Career': 'Warrior Priest', 'Human_Start': '100', 'Human_End': '100', 'Dwarf_Start': '0', 'Dwarf_End': '0', 'Halfling_Start': '0', 'Halfling_End': '0', 'High_Elf_Start': '0', 'High_Elf_End': '0', 'Wood_Elf_Start': '0', 'Wood_Elf_End': '0'}
            ,
            ]

    for row in data:
        ch_class = Class.objects.get(name=row['Class'])
        career = Career(name = row['Career'],
                            random_table_human_start =    int(row["Human_Start"]),
                            random_table_human_end =      int(row["Human_End"]),
                            random_table_dwarf_start =    int(row["Dwarf_Start"]),
                            random_table_dwarf_end =      int(row["Dwarf_End"]),
                            random_table_halfling_start = int(row["Halfling_Start"]),
                            random_table_halfling_end =   int(row["Halfling_End"]),
                            random_table_high_elf_start = int(row["High_Elf_Start"]),
                            random_table_high_elf_end =   int(row["High_Elf_End"]),
                            random_table_wood_elf_start = int(row["Wood_Elf_Start"]),
                            random_table_wood_elf_end =   int(row["Wood_Elf_End"]),
                         )
        career.ch_class = ch_class
        career.save()


class Migration(migrations.Migration):

    dependencies = [
        ('WarhammerFantasyRoleplayVirtualGM_app', '0010_auto_20230808_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='ch_class',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='WarhammerFantasyRoleplayVirtualGM_app.class', verbose_name='Class'),
        ),
        migrations.AddField(
            model_name='career',
            name='random_table_dwarf_end',
            field=models.IntegerField(default='0', verbose_name='random_table_dwarf_end'),
        ),
        migrations.AddField(
            model_name='career',
            name='random_table_dwarf_start',
            field=models.IntegerField(default='0', verbose_name='random_table_dwarf_start'),
        ),
        migrations.AddField(
            model_name='career',
            name='random_table_halfling_end',
            field=models.IntegerField(default='0', verbose_name='random_table_halfling_end'),
        ),
        migrations.AddField(
            model_name='career',
            name='random_table_halfling_start',
            field=models.IntegerField(default='0', verbose_name='random_table_halfling_start'),
        ),
        migrations.AddField(
            model_name='career',
            name='random_table_high_elf_end',
            field=models.IntegerField(default='0', verbose_name='random_table_high_elf_end'),
        ),
        migrations.AddField(
            model_name='career',
            name='random_table_high_elf_start',
            field=models.IntegerField(default='0', verbose_name='random_table_high_elf_start'),
        ),
        migrations.AddField(
            model_name='career',
            name='random_table_human_end',
            field=models.IntegerField(default='0', verbose_name='random_table_human_end'),
        ),
        migrations.AddField(
            model_name='career',
            name='random_table_human_start',
            field=models.IntegerField(default='0', verbose_name='random_table_human_start'),
        ),
        migrations.AddField(
            model_name='career',
            name='random_table_wood_elf_end',
            field=models.IntegerField(default='0', verbose_name='random_table_wood_elf_end'),
        ),
        migrations.AddField(
            model_name='career',
            name='random_table_wood_elf_start',
            field=models.IntegerField(default='0', verbose_name='random_table_wood_elf_start'),
        ),
        migrations.RunPython(add_Class_Career),
    ]
