# Generated by Django 3.2.19 on 2023-07-26 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WarhammerFantasyRoleplayVirtualGM_app', '0010_auto_20230726_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='campaign',
        ),
        migrations.CreateModel(
            name='Campaign2Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='WarhammerFantasyRoleplayVirtualGM_app.campaign')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='WarhammerFantasyRoleplayVirtualGM_app.player')),
            ],
        ),
    ]
