# Generated by Django 3.2.19 on 2023-07-27 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WarhammerFantasyRoleplayVirtualGM_app', '0011_auto_20230726_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign2player',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WarhammerFantasyRoleplayVirtualGM_app.campaign'),
        ),
        migrations.AlterField(
            model_name='campaign2player',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WarhammerFantasyRoleplayVirtualGM_app.player'),
        ),
    ]
