# Generated by Django 3.2.19 on 2023-08-08 18:29

from django.db import migrations, models
import django.db.models.deletion

from WarhammerFantasyRoleplayVirtualGM_app.models import Class
from WarhammerFantasyRoleplayVirtualGM_app.models import Career

class Migration(migrations.Migration):

    dependencies = [
        ('WarhammerFantasyRoleplayVirtualGM_app', '0011_auto_20230808_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='ch_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WarhammerFantasyRoleplayVirtualGM_app.class', verbose_name='Class'),
        ),
    ]
