# Generated by Django 3.2.19 on 2023-08-11 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WarhammerFantasyRoleplayVirtualGM_app', '0012_auto_20230808_2029'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CharacterClass',
        ),
    ]
