# Generated by Django 3.2.19 on 2023-08-29 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WarhammerFantasyRoleplayVirtualGM_app', '0012_armour_armourlocations'),
    ]

    operations = [
        migrations.AddField(
            model_name='trapping',
            name='encumbrance',
            field=models.IntegerField(default=1, verbose_name='Encumbrance'),
        ),
        migrations.AlterField(
            model_name='armour',
            name='armour_type',
            field=models.CharField(choices=[('SOFT LEATHER', 'SOFT LEATHER'), ('BOILED LEATHER', 'BOILED LEATHER'), ('MAIL', 'MAIL'), ('PLATE', 'PLATE')], default='SOFT LEATHER', max_length=14, verbose_name='Armour Type'),
        ),
        migrations.AlterField(
            model_name='armour',
            name='encumbrance',
            field=models.IntegerField(default=1, verbose_name='Encumbrance'),
        ),
        migrations.AlterField(
            model_name='armour',
            name='penalty',
            field=models.CharField(default='-', max_length=250, verbose_name='Penalty'),
        ),
        migrations.AlterField(
            model_name='armour',
            name='qualities_and_flaws',
            field=models.CharField(default='-', max_length=250, verbose_name='Qualities & Flaws'),
        ),
    ]
