# Generated by Django 3.2.19 on 2023-08-11 17:17

from django.db import migrations, models
import django.db.models.deletion

from WarhammerFantasyRoleplayVirtualGM_app.models import RandomAttributesTable
from WarhammerFantasyRoleplayVirtualGM_app.models import Species

class Migration(migrations.Migration):

    dependencies = [
        ('WarhammerFantasyRoleplayVirtualGM_app', '0013_delete_characterclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomAttributesTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weapon_skill', models.IntegerField(default='0', verbose_name='weapon_skill')),
                ('ballistic_skill', models.IntegerField(default='0', verbose_name='ballistic_skill')),
                ('strength', models.IntegerField(default='0', verbose_name='strength')),
                ('toughness', models.IntegerField(default='0', verbose_name='toughness')),
                ('initiative', models.IntegerField(default='0', verbose_name='initiative')),
                ('agility', models.IntegerField(default='0', verbose_name='agility')),
                ('dexterity', models.IntegerField(default='0', verbose_name='dexterity')),
                ('intelligence', models.IntegerField(default='0', verbose_name='intelligence')),
                ('willpower', models.IntegerField(default='0', verbose_name='willpower')),
                ('fellowship', models.IntegerField(default='0', verbose_name='fellowship')),
                ('fate', models.IntegerField(default='0', verbose_name='fate')),
                ('resilience', models.IntegerField(default='0', verbose_name='resilience')),
                ('extra_points', models.IntegerField(default='0', verbose_name='extra_points')),
                ('movement', models.IntegerField(default='0', verbose_name='movement')),
                ('species', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WarhammerFantasyRoleplayVirtualGM_app.species', verbose_name='Species')),
            ],
        ),
    ]
