# Generated by Django 3.2.19 on 2023-08-29 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WarhammerFantasyRoleplayVirtualGM_app', '0013_auto_20230829_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trapping',
            name='encumbrance',
        ),
    ]
