# Generated by Django 3.2.19 on 2023-08-29 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WarhammerFantasyRoleplayVirtualGM_app', '0014_remove_trapping_encumbrance'),
    ]

    operations = [
        migrations.AddField(
            model_name='trapping',
            name='encumbrance',
            field=models.IntegerField(default=1, verbose_name='Encumbrance'),
        ),
    ]
