# Generated by Django 3.2.19 on 2023-08-11 17:17

from django.db import migrations, models
import django.db.models.deletion

from WarhammerFantasyRoleplayVirtualGM_app.models import RandomAttributesTable
from WarhammerFantasyRoleplayVirtualGM_app.models import Species

def add_AttributesTable(apps, schema_editor):
    data = [
        {'species': Species.objects.get(id=2),
        'weapon_skill': 20,
        'ballistic_skill': 20,
        'strength': 20,
        'toughness': 20,
        'initiative': 20,
        'agility': 20,
        'dexterity': 20,
        'intelligence': 20,
        'willpower': 20,
        'fellowship': 20,
        'fate': 2,
        'resilience': 1,
        'extra_points': 3,
        'movement': 4,
        },
        {'species': Species.objects.get(id=4),
        'weapon_skill': 30,
        'ballistic_skill': 20,
        'strength': 20,
        'toughness': 30,
        'initiative': 20,
        'agility': 10,
        'dexterity': 30,
        'intelligence': 20,
        'willpower': 40,
        'fellowship': 10,
        'fate': 0,
        'resilience': 2,
        'extra_points': 2,
        'movement': 3,
        },
        {'species': Species.objects.get(id=3),
        'weapon_skill': 10,
        'ballistic_skill': 30,
        'strength': 10,
        'toughness': 20,
        'initiative': 20,
        'agility': 20,
        'dexterity': 30,
        'intelligence': 20,
        'willpower': 30,
        'fellowship': 30,
        'fate': 0,
        'resilience': 2,
        'extra_points': 3,
        'movement': 3,
        },
        {'species': Species.objects.get(id=1),
        'weapon_skill': 30,
        'ballistic_skill': 30,
        'strength': 20,
        'toughness': 20,
        'initiative': 40,
        'agility': 30,
        'dexterity': 30,
        'intelligence': 30,
        'willpower': 30,
        'fellowship': 20,
        'fate': 0,
        'resilience': 0,
        'extra_points': 2,
        'movement': 5,
        },
        {'species': Species.objects.get(id=5),
        'weapon_skill': 30,
        'ballistic_skill': 30,
        'strength': 20,
        'toughness': 20,
        'initiative': 40,
        'agility': 30,
        'dexterity': 30,
        'intelligence': 30,
        'willpower': 30,
        'fellowship': 20,
        'fate': 0,
        'resilience': 0,
        'extra_points': 2,
        'movement': 5,
        },
    ]

    for d in data:
        r = RandomAttributesTable(
            species         = d['species'],
            weapon_skill    = d['weapon_skill'],
            ballistic_skill = d['ballistic_skill'],
            strength        = d['strength'],
            toughness       = d['toughness'],
            initiative      = d['initiative'],
            agility         = d['agility'],
            dexterity       = d['dexterity'],
            intelligence    = d['intelligence'],
            willpower       = d['willpower'],
            fellowship      = d['fellowship'],
            fate            = d['fate'],
            resilience      = d['resilience'],
            extra_points    = d['extra_points'],
            movement        = d['movement']
        )

        r.save()


class Migration(migrations.Migration):

    dependencies = [
        ('WarhammerFantasyRoleplayVirtualGM_app', '0014_randomattributestable'),
    ]

    operations = [
        migrations.RunPython(add_AttributesTable),
    ]
