# Generated by Django 3.2.19 on 2023-08-11 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WarhammerFantasyRoleplayVirtualGM_app', '0015_randomattributestable'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='wounds',
            field=models.IntegerField(default='0', verbose_name='wounds'),
        ),
    ]
