# Generated by Django 3.2.19 on 2023-08-15 08:48

from django.db import migrations, models
import django.db.models.deletion

from WarhammerFantasyRoleplayVirtualGM_app.models import Eyes, Hair, Species

def add_Eye_and_Hair_Colors(apps, schema_editor):
    data = [
        {'species': Species.objects.get(name='Human'), 'random_table_start': 1,  'random_table_end': 2,  'Eye_name': "Green",        'Hair_name': "White Blond"},
        {'species': Species.objects.get(name='Human'), 'random_table_start': 3,  'random_table_end': 3,  'Eye_name': "Green",        'Hair_name': "Golden Blond"},
        {'species': Species.objects.get(name='Human'), 'random_table_start': 4,  'random_table_end': 4,  'Eye_name': "Pale Blue",    'Hair_name': "Red Blond"},
        {'species': Species.objects.get(name='Human'), 'random_table_start': 5,  'random_table_end': 7,  'Eye_name': "Blue",         'Hair_name': "Golden Brown"},
        {'species': Species.objects.get(name='Human'), 'random_table_start': 8,  'random_table_end': 11, 'Eye_name': "Pale Grey",    'Hair_name': "Light Brown"},
        {'species': Species.objects.get(name='Human'), 'random_table_start': 12, 'random_table_end': 14, 'Eye_name': "Grey",         'Hair_name': "Dark Brown"},
        {'species': Species.objects.get(name='Human'), 'random_table_start': 15, 'random_table_end': 17, 'Eye_name': "Brow",         'Hair_name': "Black"},
        {'species': Species.objects.get(name='Human'), 'random_table_start': 18, 'random_table_end': 18, 'Eye_name': "Hazel",        'Hair_name': "Auburn"},
        {'species': Species.objects.get(name='Human'), 'random_table_start': 19, 'random_table_end': 19, 'Eye_name': "Dark Brown",   'Hair_name': "Red"},
        {'species': Species.objects.get(name='Human'), 'random_table_start': 20, 'random_table_end': 20, 'Eye_name': "Black",        'Hair_name': "Grey"},

        {'species': Species.objects.get(name='Dwarf'), 'random_table_start': 1,  'random_table_end': 2,  'Eye_name': "Coal",        'Hair_name': "White"},
        {'species': Species.objects.get(name='Dwarf'), 'random_table_start': 3,  'random_table_end': 3,  'Eye_name': "Lead",        'Hair_name': "Golden Blond"},
        {'species': Species.objects.get(name='Dwarf'), 'random_table_start': 4,  'random_table_end': 4,  'Eye_name': "Steel",       'Hair_name': "Pale Blond"},
        {'species': Species.objects.get(name='Dwarf'), 'random_table_start': 5,  'random_table_end': 7,  'Eye_name': "Blue",        'Hair_name': "Golden"},
        {'species': Species.objects.get(name='Dwarf'), 'random_table_start': 8,  'random_table_end': 11, 'Eye_name': "Earth Brown", 'Hair_name': "Copper"},
        {'species': Species.objects.get(name='Dwarf'), 'random_table_start': 12, 'random_table_end': 14, 'Eye_name': "Dark Brown",  'Hair_name': "Bronze"},
        {'species': Species.objects.get(name='Dwarf'), 'random_table_start': 15, 'random_table_end': 17, 'Eye_name': "Hazel",       'Hair_name': "Brown"},
        {'species': Species.objects.get(name='Dwarf'), 'random_table_start': 18, 'random_table_end': 18, 'Eye_name': "Green",       'Hair_name': "Dark Brown"},
        {'species': Species.objects.get(name='Dwarf'), 'random_table_start': 19, 'random_table_end': 19, 'Eye_name': "Copper",      'Hair_name': "Reddish Brown"},
        {'species': Species.objects.get(name='Dwarf'), 'random_table_start': 20, 'random_table_end': 20, 'Eye_name': "Gold",        'Hair_name': "Black"},

        {'species': Species.objects.get(name='Halfling'), 'random_table_start': 1,  'random_table_end': 2,  'Eye_name': "Light Grey",   'Hair_name': "Grey"},
        {'species': Species.objects.get(name='Halfling'), 'random_table_start': 3,  'random_table_end': 3,  'Eye_name': "Grey",         'Hair_name': "Flaxen"},
        {'species': Species.objects.get(name='Halfling'), 'random_table_start': 4,  'random_table_end': 4,  'Eye_name': "Pale Blue",    'Hair_name': "Russet"},
        {'species': Species.objects.get(name='Halfling'), 'random_table_start': 5,  'random_table_end': 7,  'Eye_name': "Blue",         'Hair_name': "Honey"},
        {'species': Species.objects.get(name='Halfling'), 'random_table_start': 8,  'random_table_end': 11, 'Eye_name': "Green",        'Hair_name': "Chestnut"},
        {'species': Species.objects.get(name='Halfling'), 'random_table_start': 12, 'random_table_end': 14, 'Eye_name': "Hazel",        'Hair_name': "Ginger"},
        {'species': Species.objects.get(name='Halfling'), 'random_table_start': 15, 'random_table_end': 17, 'Eye_name': "Brown",        'Hair_name': "Mustard"},
        {'species': Species.objects.get(name='Halfling'), 'random_table_start': 18, 'random_table_end': 18, 'Eye_name': "Copper",       'Hair_name': "Almond"},
        {'species': Species.objects.get(name='Halfling'), 'random_table_start': 19, 'random_table_end': 19, 'Eye_name': "Dark Brown",   'Hair_name': "Chocolate"},
        {'species': Species.objects.get(name='Halfling'), 'random_table_start': 20, 'random_table_end': 20, 'Eye_name': "Dark Brown",   'Hair_name': "Liquorice"},

        {'species': Species.objects.get(name='High Elf'), 'random_table_start': 1,  'random_table_end': 2,  'Eye_name': "Jet",          'Hair_name': "Silver"},
        {'species': Species.objects.get(name='High Elf'), 'random_table_start': 3,  'random_table_end': 3,  'Eye_name': "Amethyst",     'Hair_name': "White"},
        {'species': Species.objects.get(name='High Elf'), 'random_table_start': 4,  'random_table_end': 4,  'Eye_name': "Aquamarine",   'Hair_name': "Pale Blond"},
        {'species': Species.objects.get(name='High Elf'), 'random_table_start': 5,  'random_table_end': 7,  'Eye_name': "Sapphire",     'Hair_name': "Blond"},
        {'species': Species.objects.get(name='High Elf'), 'random_table_start': 8,  'random_table_end': 11, 'Eye_name': "Turquoise",    'Hair_name': "Yellow Blond"},
        {'species': Species.objects.get(name='High Elf'), 'random_table_start': 12, 'random_table_end': 14, 'Eye_name': "Emerald",      'Hair_name': "Copper Blond"},
        {'species': Species.objects.get(name='High Elf'), 'random_table_start': 15, 'random_table_end': 17, 'Eye_name': "Amber",        'Hair_name': "Red Blond"},
        {'species': Species.objects.get(name='High Elf'), 'random_table_start': 18, 'random_table_end': 18, 'Eye_name': "Copper",       'Hair_name': "Auburn"},
        {'species': Species.objects.get(name='High Elf'), 'random_table_start': 19, 'random_table_end': 19, 'Eye_name': "Citrine",      'Hair_name': "Red"},
        {'species': Species.objects.get(name='High Elf'), 'random_table_start': 20, 'random_table_end': 20, 'Eye_name': "Gold",         'Hair_name': "Black"},

        {'species': Species.objects.get(name='Wood Elf'), 'random_table_start': 1,  'random_table_end': 2,  'Eye_name': "Ivory",        'Hair_name': "Birch Silver"},
        {'species': Species.objects.get(name='Wood Elf'), 'random_table_start': 3,  'random_table_end': 3,  'Eye_name': "Charcoal",     'Hair_name': "Ash Blond"},
        {'species': Species.objects.get(name='Wood Elf'), 'random_table_start': 4,  'random_table_end': 4,  'Eye_name': "Ivy Green",    'Hair_name': "Rose Gold"},
        {'species': Species.objects.get(name='Wood Elf'), 'random_table_start': 5,  'random_table_end': 7,  'Eye_name': "Ivy Green",    'Hair_name': "Honey Blond"},
        {'species': Species.objects.get(name='Wood Elf'), 'random_table_start': 8,  'random_table_end': 11, 'Eye_name': "Chestnut",     'Hair_name': "Brown"},
        {'species': Species.objects.get(name='Wood Elf'), 'random_table_start': 12, 'random_table_end': 14, 'Eye_name': "Chestnut",     'Hair_name': "Mahogany Brown"},
        {'species': Species.objects.get(name='Wood Elf'), 'random_table_start': 15, 'random_table_end': 17, 'Eye_name': "Dark Brown",   'Hair_name': "Dark brown"},
        {'species': Species.objects.get(name='Wood Elf'), 'random_table_start': 18, 'random_table_end': 18, 'Eye_name': "Tan",          'Hair_name': "Sienna"},
        {'species': Species.objects.get(name='Wood Elf'), 'random_table_start': 19, 'random_table_end': 19, 'Eye_name': "Sandy Brown",  'Hair_name': "Ebony"},
        {'species': Species.objects.get(name='Wood Elf'), 'random_table_start': 20, 'random_table_end': 20, 'Eye_name': "Violet",       'Hair_name': "Blue-Black"},
    ]

    for d in data:
        h = Hair(name = d['Hair_name'], species = d['species'], random_table_start = d['random_table_start'], random_table_end = d['random_table_end'])
        h.save()
        e = Eyes(name = d['Hair_name'], species = d['species'], random_table_start = d['random_table_start'], random_table_end = d['random_table_end'])
        e.save()

class Migration(migrations.Migration):

    dependencies = [
        ('WarhammerFantasyRoleplayVirtualGM_app', '0017_auto_20230813_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='eyes',
            name='random_table_end',
            field=models.IntegerField(default='0', verbose_name='random_table_human_end'),
        ),
        migrations.AddField(
            model_name='eyes',
            name='random_table_start',
            field=models.IntegerField(default='0', verbose_name='random_table_human_start'),
        ),
        migrations.AddField(
            model_name='eyes',
            name='species',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WarhammerFantasyRoleplayVirtualGM_app.species', verbose_name='Species'),
        ),
        migrations.AddField(
            model_name='hair',
            name='random_table_end',
            field=models.IntegerField(default='0', verbose_name='random_table_human_end'),
        ),
        migrations.AddField(
            model_name='hair',
            name='random_table_start',
            field=models.IntegerField(default='0', verbose_name='random_table_human_start'),
        ),
        migrations.AddField(
            model_name='hair',
            name='species',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WarhammerFantasyRoleplayVirtualGM_app.species', verbose_name='Species'),
        ),
        migrations.RunPython(add_Eye_and_Hair_Colors),
    ]
