# Generated by Django 3.2.19 on 2023-09-02 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WarhammerFantasyRoleplayVirtualGM_app', '0018_character_armour'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='weapon',
            field=models.ManyToManyField(to='WarhammerFantasyRoleplayVirtualGM_app.Weapon', verbose_name='Weapon'),
        ),
    ]
