# Generated by Django 3.2.19 on 2023-08-15 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WarhammerFantasyRoleplayVirtualGM_app', '0018_auto_20230815_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='skils',
            name='ref',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='WarhammerFantasyRoleplayVirtualGM_app.reference'),
        ),
    ]
