# Generated by Django 3.2.19 on 2023-09-02 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WarhammerFantasyRoleplayVirtualGM_app', '0019_character_weapon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spells',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('spellLists', models.CharField(choices=[('PETTY_SPELLS', 'Petty Spells'), ('ARCANE_SPELLS', 'Arcane Spells'), ('THE_LORE_OF_BEASTS', 'The Lore of Beasts'), ('THE_LORE_OF_DEATH', 'The Lore of Death'), ('THE_LORE_OF_FIRE', 'The Lore of Fire'), ('THE_LORE_OF_HEAVENS', 'The Lore of Heavens'), ('THE_LORE_OF_METAL', 'The Lore of Metal'), ('THE_LORE_OF_LIFE', 'The Lore of Life'), ('THE_LORE_OF_LIGHT', 'The Lore of Light'), ('THE_LORE_OF_SHADOWS', 'The Lore of Shadows'), ('THE_LORE_OF_HEDGECRAFT', 'The Lore of Hedgecraft'), ('THE_LORE_OF_WITCHCRAFT', 'The Lore of Witchcraft'), ('THE_LORE_OF_DAEMONOLOGY', 'The Lore of Daemonology'), ('THE_LORE_OF_NECROMANCY', 'Lore of Necromancy'), ('THE_LORE_OF_NURGLE', 'The Lore of Nurgle'), ('THE_LORE_OF_SLAANESH', 'The Lore of Slaanesh'), ('THE_LORE_OF_TZEENTCH', 'The Lore of Tzeentch')], default='PETTY_SPELLS', max_length=23, verbose_name='Spell List')),
                ('cn', models.IntegerField(default=0, verbose_name='cn')),
                ('range', models.CharField(max_length=50, verbose_name='Range')),
                ('target', models.CharField(max_length=50, verbose_name='Target')),
                ('duration', models.CharField(max_length=50, verbose_name='Duration')),
                ('effect', models.CharField(max_length=50, verbose_name='Effect')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='spells',
            field=models.ManyToManyField(to='WarhammerFantasyRoleplayVirtualGM_app.Spells', verbose_name='Spells'),
        ),
    ]
