# Generated by Django 3.2.19 on 2023-08-15 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WarhammerFantasyRoleplayVirtualGM_app', '0019_skils_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skils',
            name='ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WarhammerFantasyRoleplayVirtualGM_app.reference'),
        ),
    ]
