# Generated by Django 3.2.19 on 2023-09-04 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WarhammerFantasyRoleplayVirtualGM_app', '0021_alter_spells_effect'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='experience_total',
        ),
    ]
