# Generated by Django 3.2.19 on 2023-08-15 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WarhammerFantasyRoleplayVirtualGM_app', '0021_alter_skils_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(default='', verbose_name='Description')),
            ],
        ),
        migrations.AddField(
            model_name='careerpath',
            name='earning_money',
            field=models.CharField(default='default', max_length=50, verbose_name='Earning Money'),
        ),
        migrations.AddField(
            model_name='careerpath',
            name='skills',
            field=models.ManyToManyField(to='WarhammerFantasyRoleplayVirtualGM_app.Skils'),
        ),
        migrations.AddField(
            model_name='careerpath',
            name='talents',
            field=models.ManyToManyField(to='WarhammerFantasyRoleplayVirtualGM_app.Talent'),
        ),
        migrations.CreateModel(
            name='CareersAdvanceScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characteristics_ws_initial', models.IntegerField(default='0', verbose_name='ws')),
                ('characteristics_bs_initial', models.IntegerField(default='0', verbose_name='bs')),
                ('characteristics_s_initial', models.IntegerField(default='0', verbose_name='s')),
                ('characteristics_t_initial', models.IntegerField(default='0', verbose_name='t')),
                ('characteristics_i_initial', models.IntegerField(default='0', verbose_name='i')),
                ('characteristics_ag_initial', models.IntegerField(default='0', verbose_name='ag')),
                ('characteristics_dex_initial', models.IntegerField(default='0', verbose_name='dex')),
                ('characteristics_int_initial', models.IntegerField(default='0', verbose_name='int')),
                ('characteristics_wp_initial', models.IntegerField(default='0', verbose_name='wp')),
                ('characteristics_fel_initial', models.IntegerField(default='0', verbose_name='fel')),
                ('advances_level_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advances_level_1', to='WarhammerFantasyRoleplayVirtualGM_app.careerpath')),
                ('advances_level_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advances_level_2', to='WarhammerFantasyRoleplayVirtualGM_app.careerpath')),
                ('advances_level_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advances_level_3', to='WarhammerFantasyRoleplayVirtualGM_app.careerpath')),
                ('advances_level_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advances_level_4', to='WarhammerFantasyRoleplayVirtualGM_app.careerpath')),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WarhammerFantasyRoleplayVirtualGM_app.career', verbose_name='Career')),
            ],
        ),
        migrations.AddField(
            model_name='careerpath',
            name='trappings',
            field=models.ManyToManyField(to='WarhammerFantasyRoleplayVirtualGM_app.Trapping'),
        ),
    ]
