# Generated by Django 3.2.19 on 2023-08-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WarhammerFantasyRoleplayVirtualGM_app', '0022_auto_20230815_1508'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reference',
            options={'ordering': ['refBook', 'page']},
        ),
        migrations.AddField(
            model_name='talent',
            name='max',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='talent',
            name='tests',
            field=models.CharField(default='', max_length=50),
        ),
    ]
