# Generated by Django 3.2.19 on 2023-08-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WarhammerFantasyRoleplayVirtualGM_app', '0023_auto_20230815_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talent',
            name='tests',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
