# Generated by Django 3.2.19 on 2023-08-15 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WarhammerFantasyRoleplayVirtualGM_app', '0024_alter_talent_tests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talent',
            name='tests',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
