# Generated by Django 3.2.19 on 2023-09-18 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WarhammerFantasyRoleplayVirtualGM_app', '0024_character_campaign'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambitions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='', verbose_name='Shortterm')),
                ('achieved', models.BooleanField(default=False, verbose_name='status')),
            ],
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='ambitions_longterm',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='ambitions_shortterm',
        ),
        migrations.RemoveField(
            model_name='character',
            name='ambitions_longterm',
        ),
        migrations.RemoveField(
            model_name='character',
            name='ambitions_shortterm',
        ),
    ]
