# Generated by Django 3.2.19 on 2023-08-15 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WarhammerFantasyRoleplayVirtualGM_app', '0025_alter_talent_tests'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WarhammerFantasyRoleplayVirtualGM_app.reference'),
        ),
    ]
