# Generated by Django 3.2.19 on 2023-09-18 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WarhammerFantasyRoleplayVirtualGM_app', '0025_auto_20230918_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='ambitions_longterm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_ambitions_longterm', to='WarhammerFantasyRoleplayVirtualGM_app.ambitions', verbose_name='Longterm Ambitions'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='ambitions_shortterm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_ambitions_shortterm', to='WarhammerFantasyRoleplayVirtualGM_app.ambitions', verbose_name='Shortterm Ambitions'),
        ),
        migrations.AddField(
            model_name='character',
            name='ambitions_longterm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='character_ambitions_longterm', to='WarhammerFantasyRoleplayVirtualGM_app.ambitions', verbose_name='Longterm Ambitions'),
        ),
        migrations.AddField(
            model_name='character',
            name='ambitions_shortterm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='character_ambitions_shortterm', to='WarhammerFantasyRoleplayVirtualGM_app.ambitions', verbose_name='Shortterm Ambitions'),
        ),
    ]
