# Generated by Django 3.2.19 on 2023-09-18 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WarhammerFantasyRoleplayVirtualGM_app', '0026_auto_20230918_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambitions',
            name='achieved',
            field=models.BooleanField(default=False, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='ambitions',
            name='description',
            field=models.TextField(default='', verbose_name='Description'),
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='ambitions_longterm',
        ),
        migrations.AddField(
            model_name='campaign',
            name='ambitions_longterm',
            field=models.ManyToManyField(null=True, related_name='campaign_ambitions_longterm', to='WarhammerFantasyRoleplayVirtualGM_app.Ambitions', verbose_name='Longterm Ambitions'),
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='ambitions_shortterm',
        ),
        migrations.AddField(
            model_name='campaign',
            name='ambitions_shortterm',
            field=models.ManyToManyField(null=True, related_name='campaign_ambitions_shortterm', to='WarhammerFantasyRoleplayVirtualGM_app.Ambitions', verbose_name='Shortterm Ambitions'),
        ),
        migrations.RemoveField(
            model_name='character',
            name='ambitions_longterm',
        ),
        migrations.AddField(
            model_name='character',
            name='ambitions_longterm',
            field=models.ManyToManyField(null=True, related_name='character_ambitions_longterm', to='WarhammerFantasyRoleplayVirtualGM_app.Ambitions', verbose_name='Longterm Ambitions'),
        ),
        migrations.RemoveField(
            model_name='character',
            name='ambitions_shortterm',
        ),
        migrations.AddField(
            model_name='character',
            name='ambitions_shortterm',
            field=models.ManyToManyField(null=True, related_name='character_ambitions_shortterm', to='WarhammerFantasyRoleplayVirtualGM_app.Ambitions', verbose_name='Shortterm Ambitions'),
        ),
    ]
