# Generated by Django 3.2.19 on 2023-08-16 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WarhammerFantasyRoleplayVirtualGM_app', '0027_advance_scheme'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='careersadvancescheme',
            options={'ordering': ['career']},
        ),
        migrations.AddField(
            model_name='species',
            name='skills',
            field=models.ManyToManyField(to='WarhammerFantasyRoleplayVirtualGM_app.Skils'),
        ),
        migrations.AddField(
            model_name='species',
            name='talents',
            field=models.ManyToManyField(to='WarhammerFantasyRoleplayVirtualGM_app.Talent'),
        ),
    ]
