# Generated by Django 3.2.19 on 2023-09-20 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WarhammerFantasyRoleplayVirtualGM_app', '0027_auto_20230918_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='ambitions_longterm',
            field=models.ManyToManyField(related_name='campaign_ambitions_longterm', to='WarhammerFantasyRoleplayVirtualGM_app.Ambitions', verbose_name='Longterm Ambitions'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='ambitions_shortterm',
            field=models.ManyToManyField(related_name='campaign_ambitions_shortterm', to='WarhammerFantasyRoleplayVirtualGM_app.Ambitions', verbose_name='Shortterm Ambitions'),
        ),
        migrations.AlterField(
            model_name='character',
            name='ambitions_longterm',
            field=models.ManyToManyField(related_name='character_ambitions_longterm', to='WarhammerFantasyRoleplayVirtualGM_app.Ambitions', verbose_name='Longterm Ambitions'),
        ),
        migrations.AlterField(
            model_name='character',
            name='ambitions_shortterm',
            field=models.ManyToManyField(related_name='character_ambitions_shortterm', to='WarhammerFantasyRoleplayVirtualGM_app.Ambitions', verbose_name='Shortterm Ambitions'),
        ),
    ]
