# Generated by Django 3.2.19 on 2023-09-30 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WarhammerFantasyRoleplayVirtualGM_app', '0028_auto_20230920_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='wealth',
            field=models.IntegerField(default=0, verbose_name='Wealth'),
        ),
    ]
