# Generated by Django 3.2.19 on 2023-08-16 18:24

from django.db import migrations, models
import django.db.models.deletion

from WarhammerFantasyRoleplayVirtualGM_app.models import Talent
from WarhammerFantasyRoleplayVirtualGM_app.models import RandomTalentsTable

def add_RandomSkillsTable(apps, schema_editor):
    data = [
        {'talent': Talent.objects.get(name="Acute Sense (Sense)") , 'random_interal_start': 1,   'random_interal_end':1  },
        {'talent': Talent.objects.get(name="Acute Sense (Sight)") , 'random_interal_start': 2,   'random_interal_end':2  },
        {'talent': Talent.objects.get(name="Acute Sense (Taste)") , 'random_interal_start': 3,   'random_interal_end':3  },
        {'talent': Talent.objects.get(name="Ambidextrous") ,        'random_interal_start': 4,   'random_interal_end':6  },
        {'talent': Talent.objects.get(name="Animal Affinity") ,     'random_interal_start': 7,   'random_interal_end':9  },
        {'talent': Talent.objects.get(name="Artistic") ,            'random_interal_start': 10,  'random_interal_end':12 },
        {'talent': Talent.objects.get(name="Attractive") ,          'random_interal_start': 13,  'random_interal_end':15 },
        {'talent': Talent.objects.get(name="Coolheaded") ,          'random_interal_start': 16,  'random_interal_end':18 },
        {'talent': Talent.objects.get(name="Craftsman (Trade)") ,   'random_interal_start': 19,  'random_interal_end':21 },
        {'talent': Talent.objects.get(name="Flee!") ,               'random_interal_start': 22,  'random_interal_end':24 },
        {'talent': Talent.objects.get(name="Hardy") ,               'random_interal_start': 25,  'random_interal_end':28 },
        {'talent': Talent.objects.get(name="Lightning Reflexes") ,  'random_interal_start': 29,  'random_interal_end':31 },
        {'talent': Talent.objects.get(name="Linguistics") ,         'random_interal_start': 32,  'random_interal_end':34 },
        {'talent': Talent.objects.get(name="Luck") ,                'random_interal_start': 35,  'random_interal_end':38 },
        {'talent': Talent.objects.get(name="Marksman") ,            'random_interal_start': 39,  'random_interal_end':41 },
        {'talent': Talent.objects.get(name="Mimic") ,               'random_interal_start': 42,  'random_interal_end':44 },
        {'talent': Talent.objects.get(name="Night Vision") ,        'random_interal_start': 45,  'random_interal_end':47 },
        {'talent': Talent.objects.get(name="Nimble Fingered") ,     'random_interal_start': 48,  'random_interal_end':50 },
        {'talent': Talent.objects.get(name="Noble Blood") ,         'random_interal_start': 51,  'random_interal_end':52 },
        {'talent': Talent.objects.get(name="Orientation") ,         'random_interal_start': 53,  'random_interal_end':55 },
        {'talent': Talent.objects.get(name="Perfect Pitch") ,       'random_interal_start': 56,  'random_interal_end':58 },
        {'talent': Talent.objects.get(name="Pure Soul") ,           'random_interal_start': 59,  'random_interal_end':62 },
        {'talent': Talent.objects.get(name="Read/Write") ,          'random_interal_start': 63,  'random_interal_end':65 },
        {'talent': Talent.objects.get(name="Resistance (Chaos)") ,          'random_interal_start': 66,  'random_interal_end':68 },
        {'talent': Talent.objects.get(name="Savvy") ,               'random_interal_start': 69,  'random_interal_end':71 },
        {'talent': Talent.objects.get(name="Sharp") ,               'random_interal_start': 72,  'random_interal_end':74 },
        {'talent': Talent.objects.get(name="Sixth Sense") ,         'random_interal_start': 75,  'random_interal_end':78 },
        {'talent': Talent.objects.get(name="Strong Legs") ,         'random_interal_start': 79,  'random_interal_end':81 },
        {'talent': Talent.objects.get(name="Sturdy") ,              'random_interal_start': 82,  'random_interal_end':84 },
        {'talent': Talent.objects.get(name="Suave") ,               'random_interal_start': 85,  'random_interal_end':87 },
        {'talent': Talent.objects.get(name="Super Numerate") ,      'random_interal_start': 88,  'random_interal_end':91 },
        {'talent': Talent.objects.get(name="Very Resilient") ,      'random_interal_start': 92,  'random_interal_end':94 },
        {'talent': Talent.objects.get(name="Very Strong") ,         'random_interal_start': 95,  'random_interal_end':97 },
        {'talent': Talent.objects.get(name="Warrior Born") ,        'random_interal_start': 98,  'random_interal_end':100 },
    ]

    for d in data:
        r = RandomTalentsTable(talent= d['talent'], random_interal_start=d['random_interal_start'], random_interal_end=d['random_interal_end'])
        r.save()


class Migration(migrations.Migration):

    dependencies = [
        ('WarhammerFantasyRoleplayVirtualGM_app', '0028_auto_20230816_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='random_interal_end',
            field=models.IntegerField(default=0, verbose_name='random_interal_end'),
        ),
        migrations.CreateModel(
            name='RandomTalentsTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('random_interal_start', models.IntegerField(default=0, verbose_name='random_interal_start')),
                ('random_interal_end', models.IntegerField(default=0, verbose_name='random_interal_end')),
                ('talent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WarhammerFantasyRoleplayVirtualGM_app.talent', verbose_name='Talent')),
            ],
        ),
        migrations.RunPython(add_RandomSkillsTable),
    ]
