# Generated by Django 3.2.19 on 2023-08-16 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WarhammerFantasyRoleplayVirtualGM_app', '0029_auto_20230816_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='randomtalentstable',
            name='any',
            field=models.BooleanField(default=False, verbose_name='Any'),
        ),
    ]
