# Generated by Django 3.2.19 on 2023-08-19 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WarhammerFantasyRoleplayVirtualGM_app', '0030_randomtalentstable_any'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='character2skill',
            unique_together={('characters', 'skills')},
        ),
    ]
