# Generated by Django 3.2.19 on 2023-10-09 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WarhammerFantasyRoleplayVirtualGM_app', '0030_alter_character_spells'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_create', models.DateTimeField(auto_now_add=True, verbose_name='Create TIme')),
                ('datetime_update', models.DateTimeField(auto_now=True, verbose_name='Update TIme')),
                ('note_text', models.TextField(default='', verbose_name='Note Text')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='notes',
            field=models.ManyToManyField(blank=True, null=True, to='WarhammerFantasyRoleplayVirtualGM_app.Note', verbose_name='Spells'),
        ),
    ]
