# Generated by Django 3.2.19 on 2023-10-11 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WarhammerFantasyRoleplayVirtualGM_app', '0031_auto_20231009_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='notes',
            field=models.ManyToManyField(blank=True, null=True, to='WarhammerFantasyRoleplayVirtualGM_app.Note', verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='character',
            name='notes',
            field=models.ManyToManyField(blank=True, null=True, to='WarhammerFantasyRoleplayVirtualGM_app.Note', verbose_name='Notes'),
        ),
    ]
