# Generated by Django 3.2.19 on 2023-08-19 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WarhammerFantasyRoleplayVirtualGM_app', '0031_alter_character2skill_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character2Talent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taken', models.IntegerField(default='0', verbose_name='adv')),
                ('characters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WarhammerFantasyRoleplayVirtualGM_app.character')),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WarhammerFantasyRoleplayVirtualGM_app.talent')),
            ],
            options={
                'unique_together': {('characters', 'talent')},
            },
        ),
    ]
