# Generated by Django 3.2.19 on 2023-10-28 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WarhammerFantasyRoleplayVirtualGM_app', '0032_auto_20231011_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character2trappingl',
            name='enc',
        ),
    ]
