# Generated by Django 3.2.19 on 2023-08-19 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WarhammerFantasyRoleplayVirtualGM_app', '0032_character2talent'),
    ]

    operations = [
        migrations.AddField(
            model_name='character2skill',
            name='type',
            field=models.CharField(choices=[('BS', 'BASIC SKILL'), ('NS', 'NORMAL SKILL')], default='BS', max_length=2),
        ),
    ]
