# Generated by Django 3.2.19 on 2023-11-23 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WarhammerFantasyRoleplayVirtualGM_app', '0033_remove_character2trappingl_enc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armour',
            name='availability',
            field=models.CharField(choices=[('Common', 'Common'), ('Scarce', 'Scarce'), ('Rare', 'Rare'), ('Exotic', 'Exotic')], default='Common', max_length=6, verbose_name='Availability'),
        ),
        migrations.AlterField(
            model_name='character',
            name='height',
            field=models.IntegerField(default='1', verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='meleeweapons',
            name='reach',
            field=models.CharField(choices=[('AVERAGE', 'Average'), ('LONG', 'Long'), ('MASSIVE', 'Massive'), ('MEDIUM', 'Medium'), ('PERSONAL', 'Personal'), ('SHORT', 'Short'), ('VARIES', 'Varies'), ('VERY_LONG', 'Very Long'), ('VERY_SHORT', 'Very Short')], default='VERY_SHORT', max_length=14, verbose_name='Reach'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='availability',
            field=models.CharField(choices=[('Common', 'Common'), ('Scarce', 'Scarce'), ('Rare', 'Rare'), ('Exotic', 'Exotic')], default='Common', max_length=6, verbose_name='Availability'),
        ),
    ]
