# Generated by Django 3.2.19 on 2023-08-19 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WarhammerFantasyRoleplayVirtualGM_app', '0033_character2skill_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careersadvancescheme',
            name='characteristics_ag_initial',
            field=models.CharField(choices=[('NO', 'NONE'), ('CR', 'CROSS'), ('HA', 'HALBERD'), ('SK', 'SKULL'), ('SH', 'SHIELD')], default='NO', max_length=2),
        ),
        migrations.AlterField(
            model_name='careersadvancescheme',
            name='characteristics_bs_initial',
            field=models.CharField(choices=[('NO', 'NONE'), ('CR', 'CROSS'), ('HA', 'HALBERD'), ('SK', 'SKULL'), ('SH', 'SHIELD')], default='NO', max_length=2),
        ),
        migrations.AlterField(
            model_name='careersadvancescheme',
            name='characteristics_dex_initial',
            field=models.CharField(choices=[('NO', 'NONE'), ('CR', 'CROSS'), ('HA', 'HALBERD'), ('SK', 'SKULL'), ('SH', 'SHIELD')], default='NO', max_length=2),
        ),
        migrations.AlterField(
            model_name='careersadvancescheme',
            name='characteristics_fel_initial',
            field=models.CharField(choices=[('NO', 'NONE'), ('CR', 'CROSS'), ('HA', 'HALBERD'), ('SK', 'SKULL'), ('SH', 'SHIELD')], default='NO', max_length=2),
        ),
        migrations.AlterField(
            model_name='careersadvancescheme',
            name='characteristics_i_initial',
            field=models.CharField(choices=[('NO', 'NONE'), ('CR', 'CROSS'), ('HA', 'HALBERD'), ('SK', 'SKULL'), ('SH', 'SHIELD')], default='NO', max_length=2),
        ),
        migrations.AlterField(
            model_name='careersadvancescheme',
            name='characteristics_int_initial',
            field=models.CharField(choices=[('NO', 'NONE'), ('CR', 'CROSS'), ('HA', 'HALBERD'), ('SK', 'SKULL'), ('SH', 'SHIELD')], default='NO', max_length=2),
        ),
        migrations.AlterField(
            model_name='careersadvancescheme',
            name='characteristics_s_initial',
            field=models.CharField(choices=[('NO', 'NONE'), ('CR', 'CROSS'), ('HA', 'HALBERD'), ('SK', 'SKULL'), ('SH', 'SHIELD')], default='NO', max_length=2),
        ),
        migrations.AlterField(
            model_name='careersadvancescheme',
            name='characteristics_t_initial',
            field=models.CharField(choices=[('NO', 'NONE'), ('CR', 'CROSS'), ('HA', 'HALBERD'), ('SK', 'SKULL'), ('SH', 'SHIELD')], default='NO', max_length=2),
        ),
        migrations.AlterField(
            model_name='careersadvancescheme',
            name='characteristics_wp_initial',
            field=models.CharField(choices=[('NO', 'NONE'), ('CR', 'CROSS'), ('HA', 'HALBERD'), ('SK', 'SKULL'), ('SH', 'SHIELD')], default='NO', max_length=2),
        ),
        migrations.AlterField(
            model_name='careersadvancescheme',
            name='characteristics_ws_initial',
            field=models.CharField(choices=[('NO', 'NONE'), ('CR', 'CROSS'), ('HA', 'HALBERD'), ('SK', 'SKULL'), ('SH', 'SHIELD')], default='NO', max_length=2),
        ),
    ]
