# Generated by Django 3.2.19 on 2023-11-28 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('WarhammerFantasyRoleplayVirtualGM_app', '0033_remove_character2trappingl_enc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armour',
            name='availability',
            field=models.CharField(choices=[('Common', 'Common'), ('Scarce', 'Scarce'), ('Rare', 'Rare'), ('Exotic', 'Exotic')], default='Common', max_length=6, verbose_name='Availability'),
        ),
        migrations.AlterField(
            model_name='character',
            name='height',
            field=models.IntegerField(default='1', verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='meleeweapons',
            name='reach',
            field=models.CharField(choices=[('AVERAGE', 'Average'), ('LONG', 'Long'), ('MASSIVE', 'Massive'), ('MEDIUM', 'Medium'), ('PERSONAL', 'Personal'), ('SHORT', 'Short'), ('VARIES', 'Varies'), ('VERY_LONG', 'Very Long'), ('VERY_SHORT', 'Very Short')], default='VERY_SHORT', max_length=14, verbose_name='Reach'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='availability',
            field=models.CharField(choices=[('Common', 'Common'), ('Scarce', 'Scarce'), ('Rare', 'Rare'), ('Exotic', 'Exotic')], default='Common', max_length=6, verbose_name='Availability'),
        ),
        migrations.CreateModel(
            name='CharacterChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_create', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('log', models.TextField(default='', verbose_name='Log')),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='WarhammerFantasyRoleplayVirtualGM_app.character', verbose_name='Character')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
