# Generated by Django 3.2.19 on 2023-08-19 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WarhammerFantasyRoleplayVirtualGM_app', '0034_auto_20230819_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trapping',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
