# Generated by Django 3.2.19 on 2023-11-28 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('WarhammerFantasyRoleplayVirtualGM_app', '0034_auto_20231128_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterchangelog',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WarhammerFantasyRoleplayVirtualGM_app.character', verbose_name='Character'),
        ),
        migrations.AlterField(
            model_name='characterchangelog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
