# Generated by Django 3.2.19 on 2023-08-20 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WarhammerFantasyRoleplayVirtualGM_app', '0035_alter_trapping_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerpath',
            name='careerpath_descendants',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='WarhammerFantasyRoleplayVirtualGM_app.careerpath'),
        ),
    ]
