# Generated by Django 3.2.19 on 2023-11-29 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WarhammerFantasyRoleplayVirtualGM_app', '0035_auto_20231128_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Containers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('encumbrance', models.IntegerField(default=0, verbose_name='Encumbrance')),
                ('carries', models.IntegerField(default=0, verbose_name='Carries')),
                ('price', models.IntegerField(default=0, verbose_name='Price')),
                ('availability', models.CharField(choices=[('Common', 'Common'), ('Scarce', 'Scarce'), ('Rare', 'Rare'), ('Exotic', 'Exotic')], default='Common', max_length=6, verbose_name='Availability')),
            ],
        ),
    ]
