# Generated by Django 3.2.19 on 2023-12-11 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WarhammerFantasyRoleplayVirtualGM_app', '0036_containers'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WarhammerFantasyRoleplayVirtualGM_app.containers', verbose_name='Player')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WarhammerFantasyRoleplayVirtualGM_app.player', verbose_name='Player')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerContainerItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_melee_weapon', models.ManyToManyField(blank=True, null=True, to='WarhammerFantasyRoleplayVirtualGM_app.MeleeWeapons', verbose_name='Melee Weapons')),
                ('item_ranged_weapon', models.ManyToManyField(blank=True, null=True, to='WarhammerFantasyRoleplayVirtualGM_app.RangedWeapon', verbose_name='Ranged Weapon')),
                ('item_trapping', models.ManyToManyField(blank=True, null=True, to='WarhammerFantasyRoleplayVirtualGM_app.Trapping', verbose_name='Trapping')),
                ('playerContainer', models.ManyToManyField(to='WarhammerFantasyRoleplayVirtualGM_app.PlayerContainer', verbose_name='Player')),
            ],
        ),
    ]
