# Generated by Django 3.2.19 on 2023-08-20 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WarhammerFantasyRoleplayVirtualGM_app', '0036_careerpath_careerpath_descendants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careerpath',
            name='careerpath_descendants',
        ),
    ]
