# Generated by Django 3.2.19 on 2023-12-11 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WarhammerFantasyRoleplayVirtualGM_app', '0037_playercontainer_playercontaineritems'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WarhammerFantasyRoleplayVirtualGM_app.character', verbose_name='Character')),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WarhammerFantasyRoleplayVirtualGM_app.containers', verbose_name='Container')),
            ],
        ),
        migrations.RemoveField(
            model_name='playercontaineritems',
            name='playerContainer',
        ),
        migrations.DeleteModel(
            name='PlayerContainer',
        ),
        migrations.AddField(
            model_name='playercontaineritems',
            name='characterContainer',
            field=models.ManyToManyField(to='WarhammerFantasyRoleplayVirtualGM_app.CharacterContainer', verbose_name='Player'),
        ),
    ]
