# Generated by Django 3.2.19 on 2023-12-11 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WarhammerFantasyRoleplayVirtualGM_app', '0038_auto_20231211_2027'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlayerContainerItems',
            new_name='CharacterContainerItems',
        ),
    ]
