# Generated by Django 3.2.19 on 2023-08-23 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WarhammerFantasyRoleplayVirtualGM_app', '0038_auto_20230820_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character2skill',
            name='type',
        ),
        migrations.AddField(
            model_name='character2skill',
            name='is_basic_skill',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='character2skill',
            name='is_carrer_skill',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='character2skill',
            name='is_species_skill',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='careersadvancescheme',
            name='characteristics_ag_initial',
            field=models.CharField(choices=[('NO', ' '), ('CR', 'CROSS'), ('HA', 'HALBERD'), ('SK', 'SKULL'), ('SH', 'SHIELD')], default='NO', max_length=2, verbose_name='Agility'),
        ),
        migrations.AlterField(
            model_name='careersadvancescheme',
            name='characteristics_bs_initial',
            field=models.CharField(choices=[('NO', ' '), ('CR', 'CROSS'), ('HA', 'HALBERD'), ('SK', 'SKULL'), ('SH', 'SHIELD')], default='NO', max_length=2, verbose_name='Ballistic Skill'),
        ),
        migrations.AlterField(
            model_name='careersadvancescheme',
            name='characteristics_dex_initial',
            field=models.CharField(choices=[('NO', ' '), ('CR', 'CROSS'), ('HA', 'HALBERD'), ('SK', 'SKULL'), ('SH', 'SHIELD')], default='NO', max_length=2, verbose_name='Dexterity'),
        ),
        migrations.AlterField(
            model_name='careersadvancescheme',
            name='characteristics_fel_initial',
            field=models.CharField(choices=[('NO', ' '), ('CR', 'CROSS'), ('HA', 'HALBERD'), ('SK', 'SKULL'), ('SH', 'SHIELD')], default='NO', max_length=2, verbose_name='Fellowship'),
        ),
        migrations.AlterField(
            model_name='careersadvancescheme',
            name='characteristics_i_initial',
            field=models.CharField(choices=[('NO', ' '), ('CR', 'CROSS'), ('HA', 'HALBERD'), ('SK', 'SKULL'), ('SH', 'SHIELD')], default='NO', max_length=2, verbose_name='Initiative'),
        ),
        migrations.AlterField(
            model_name='careersadvancescheme',
            name='characteristics_int_initial',
            field=models.CharField(choices=[('NO', ' '), ('CR', 'CROSS'), ('HA', 'HALBERD'), ('SK', 'SKULL'), ('SH', 'SHIELD')], default='NO', max_length=2, verbose_name='Intelligence'),
        ),
        migrations.AlterField(
            model_name='careersadvancescheme',
            name='characteristics_s_initial',
            field=models.CharField(choices=[('NO', ' '), ('CR', 'CROSS'), ('HA', 'HALBERD'), ('SK', 'SKULL'), ('SH', 'SHIELD')], default='NO', max_length=2, verbose_name='Strength'),
        ),
        migrations.AlterField(
            model_name='careersadvancescheme',
            name='characteristics_t_initial',
            field=models.CharField(choices=[('NO', ' '), ('CR', 'CROSS'), ('HA', 'HALBERD'), ('SK', 'SKULL'), ('SH', 'SHIELD')], default='NO', max_length=2, verbose_name='Toughness'),
        ),
        migrations.AlterField(
            model_name='careersadvancescheme',
            name='characteristics_wp_initial',
            field=models.CharField(choices=[('NO', ' '), ('CR', 'CROSS'), ('HA', 'HALBERD'), ('SK', 'SKULL'), ('SH', 'SHIELD')], default='NO', max_length=2, verbose_name='Willpower'),
        ),
        migrations.AlterField(
            model_name='careersadvancescheme',
            name='characteristics_ws_initial',
            field=models.CharField(choices=[('NO', ' '), ('CR', 'CROSS'), ('HA', 'HALBERD'), ('SK', 'SKULL'), ('SH', 'SHIELD')], default='NO', max_length=2, verbose_name='Weapon Skill'),
        ),
    ]
