# Generated by Django 3.2.19 on 2023-12-11 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WarhammerFantasyRoleplayVirtualGM_app', '0039_rename_playercontaineritems_charactercontaineritems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charactercontaineritems',
            name='characterContainer',
        ),
        migrations.AddField(
            model_name='charactercontaineritems',
            name='characterContainer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='WarhammerFantasyRoleplayVirtualGM_app.charactercontainer', verbose_name='Character Container'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='charactercontaineritems',
            name='item_melee_weapon',
        ),
        migrations.AddField(
            model_name='charactercontaineritems',
            name='item_melee_weapon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='WarhammerFantasyRoleplayVirtualGM_app.meleeweapons', verbose_name='Melee Weapons'),
        ),
        migrations.RemoveField(
            model_name='charactercontaineritems',
            name='item_ranged_weapon',
        ),
        migrations.AddField(
            model_name='charactercontaineritems',
            name='item_ranged_weapon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='WarhammerFantasyRoleplayVirtualGM_app.rangedweapon', verbose_name='Ranged Weapon'),
        ),
        migrations.RemoveField(
            model_name='charactercontaineritems',
            name='item_trapping',
        ),
        migrations.AddField(
            model_name='charactercontaineritems',
            name='item_trapping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='WarhammerFantasyRoleplayVirtualGM_app.trapping', verbose_name='Trapping'),
        ),
    ]
