# Generated by Django 3.2.19 on 2023-08-26 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WarhammerFantasyRoleplayVirtualGM_app', '0039_auto_20230823_1840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character2skill',
            old_name='is_carrer_skill',
            new_name='is_career_skill',
        ),
    ]
