# Generated by Django 3.2.19 on 2023-12-30 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WarhammerFantasyRoleplayVirtualGM_app', '0041_containers_trapping'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Character2Trappingl',
            new_name='Character2Trapping',
        ),
    ]
