# Generated by Django 3.2.19 on 2023-12-30 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WarhammerFantasyRoleplayVirtualGM_app', '0042_rename_character2trappingl_character2trapping'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CharacterContainer',
            new_name='Character2Container',
        ),
        migrations.RenameModel(
            old_name='CharacterContainerItems',
            new_name='Character2ContainerItems',
        ),
    ]
