# Generated by Django 3.2.19 on 2023-12-30 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WarhammerFantasyRoleplayVirtualGM_app', '0043_auto_20231230_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='character2trapping',
            name='container',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WarhammerFantasyRoleplayVirtualGM_app.character2container'),
        ),
        migrations.DeleteModel(
            name='Character2ContainerItems',
        ),
    ]
