# Generated by Django 3.2.19 on 2023-12-30 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WarhammerFantasyRoleplayVirtualGM_app', '0044_auto_20231230_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character2trapping',
            name='container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='WarhammerFantasyRoleplayVirtualGM_app.character2container'),
        ),
    ]
