# Generated by Django 3.2.19 on 2024-01-08 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('WarhammerFantasyRoleplayVirtualGM_app', '0045_alter_character2trapping_container'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='note',
            name='datetime_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Create Time'),
        ),
        migrations.AlterField(
            model_name='note',
            name='datetime_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Update Time'),
        ),
    ]
