# Generated by Django 3.2.19 on 2024-01-08 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WarhammerFantasyRoleplayVirtualGM_app', '0046_auto_20240108_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='random_table_wood_ogre_end',
            field=models.IntegerField(default='0', verbose_name='random_table_wood_ogre_end'),
        ),
        migrations.AddField(
            model_name='career',
            name='random_table_wood_ogre_start',
            field=models.IntegerField(default='0', verbose_name='random_table_wood_ogre_start'),
        ),
    ]
