# Generated by Django 3.2.19 on 2024-02-21 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WarhammerFantasyRoleplayVirtualGM_app', '0048_condition_condition2character'),
    ]

    operations = [
        migrations.AddField(
            model_name='trapping',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Price'),
        ),
    ]
