# Generated by Django 3.2.19 on 2024-02-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WarhammerFantasyRoleplayVirtualGM_app', '0050_trapping_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='trapping',
            name='to_view',
            field=models.BooleanField(default=True, verbose_name='To View'),
        ),
    ]
