# Generated by Django 3.2.19 on 2024-02-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WarhammerFantasyRoleplayVirtualGM_app', '0051_trapping_to_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='character2trapping',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Quantity'),
        ),
    ]
