# Generated by Django 3.2.19 on 2024-02-28 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WarhammerFantasyRoleplayVirtualGM_app', '0052_character2trapping_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character2talent',
            name='is_basic_skill',
        ),
        migrations.RemoveField(
            model_name='character2talent',
            name='is_career_skill',
        ),
        migrations.RemoveField(
            model_name='character2talent',
            name='is_species_skill',
        ),
        migrations.RemoveField(
            model_name='character2trapping',
            name='is_basic_skill',
        ),
        migrations.RemoveField(
            model_name='character2trapping',
            name='is_career_skill',
        ),
        migrations.RemoveField(
            model_name='character2trapping',
            name='is_species_skill',
        ),
    ]
