# Generated by Django 3.2.19 on 2024-03-05 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WarhammerFantasyRoleplayVirtualGM_app', '0053_auto_20240228_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='career_path',
        ),
        migrations.CreateModel(
            name='Character2CareerPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WarhammerFantasyRoleplayVirtualGM_app.careerpath')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WarhammerFantasyRoleplayVirtualGM_app.character')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='career_path',
            field=models.ManyToManyField(through='WarhammerFantasyRoleplayVirtualGM_app.Character2CareerPath', to='WarhammerFantasyRoleplayVirtualGM_app.CareerPath', verbose_name='CareerPath'),
        ),
    ]
