# Generated by Django 3.2.19 on 2024-05-11 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WarhammerFantasyRoleplayVirtualGM_app', '0055_auto_20240309_1813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='wounds',
            new_name='current_wounds',
        ),
    ]
