# Generated by Django 5.0.6 on 2024-06-12 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WarhammerFantasyRoleplayVirtualGM_app', '0059_weaponqualities_weapon_qualities'),
    ]

    operations = [
        migrations.AddField(
            model_name='weaponqualities',
            name='type',
            field=models.CharField(choices=[('Qualities', 'QUALITIES'), ('Flaws', 'FLAWS')], default='Qualities', max_length=14, verbose_name='Type'),
        ),
    ]
