# Generated by Django 5.0.6 on 2024-06-12 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WarhammerFantasyRoleplayVirtualGM_app', '0060_weaponqualities_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='qualities',
            field=models.ManyToManyField(blank=True, to='WarhammerFantasyRoleplayVirtualGM_app.weaponqualities', verbose_name='Qualities & Flaws'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='qualities_and_flaws',
            field=models.CharField(default='-', max_length=250, verbose_name='Notes'),
        ),
    ]
