# Generated by Django 5.0.6 on 2024-07-03 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WarhammerFantasyRoleplayVirtualGM_app', '0061_alter_weapon_qualities_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-datetime_update']},
        ),
        migrations.AddField(
            model_name='character',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Is delated'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='qualities_and_flaws',
            field=models.CharField(blank=True, default='-', max_length=250, verbose_name='Notes'),
        ),
    ]
