# Generated by Django 5.1 on 2024-08-21 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WarhammerFantasyRoleplayVirtualGM_app', '0062_alter_note_options_character_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='coruption_and_mutation',
            field=models.TextField(default='', verbose_name='Coruption & Mutation'),
        ),
        migrations.AddField(
            model_name='character',
            name='psychology',
            field=models.TextField(default='', verbose_name='Psychology'),
        ),
    ]
