INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Accurate Shot", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Acute Sense (Sense)", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Aethyric Attunement", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Alley Cat", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Ambidextrous", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Animal Affinity", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Arcane Magic (Lore)", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Argumentative", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Artistic", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Attractive", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Battle Rage", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Beat Blade", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Beneath Notice", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Berserk Charge", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Blather", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Bless (Divine Lore)", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Bookish", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Break and Enter", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Briber", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Cardsharp", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Careful Strike", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Carouser", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Cat-tongued", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Catfall", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Chaos Magic (Lore)", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Combat Aware", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Combat Master", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Combat Reflexes", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Commanding Presence", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Concoct", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Contortionist", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Coolheaded", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Crack the Whip", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Craftsman (Trade)", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Criminal", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Deadeye Shot", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Dealmaker", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Detect Artefact", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Diceman", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Dirty Fighting", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Disarm", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Distract", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Doomed", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Drilled", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Dual Wielder", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Embezzle", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Enclosed Fighter", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Etiquette (Social Group)", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Fast Hands", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Fast Shot", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Fearless (Enemy)", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Feint", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Field Dressing", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Fisherman", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Flagellant", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Flee!", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Fleet Footed", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Frenzy", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Frightening", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Furious Assault", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Gregarious", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Gunner", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Hardy", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Hatred (Group)", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Holy Hatred", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Holy Visions", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Hunter\xe2\x80\x99s Eye", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Impassioned Zeal", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Implacable", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("In-fighter", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Inspiring", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Instinctive Diction", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Invoke (Divine Lore)", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Iron Jaw", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Iron Will", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Jump Up", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Kingpin", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Lightning Reflexes", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Linguistics", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Lip Reading", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Luck", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Magic Resistance", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Magical Sense", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Magnum Opus", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Marksman", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Master of Disguise", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Master Orator", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Master Tradesman (Trade)", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Menacing", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Mimic", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Night Vision", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Nimble Fingered", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Noble Blood", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Nose for Trouble", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Numismatics", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Old Salt", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Orientation", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Panhandle", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Perfect Pitch", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Petty Magic", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Pharmacist", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Pilot", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Public Speaker", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Pure Soul", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Rapid Reload", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Reaction Strike", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Read/Write", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Relentless", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Resistance (Threat)", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Resolute", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Reversal", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Riposte", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("River Guide", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Robust", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Roughrider", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Rover", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Savant (Lore)", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Savvy", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Scale Sheer Surface", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Schemer", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Sea Legs", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Seasoned Traveller", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Second Sight", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Secret Identity", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Shadow", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Sharp", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Sharpshooter", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Shieldsman", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Sixth Sense", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Slayer", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Small", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Sniper", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Speedreader", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Sprinter", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Step Aside", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Stone Soup", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Stout-hearted", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Strider (Terrain)", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Strike Mighty Blow", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Strike to Injure", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Strike to Stun", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Strong Back", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Strong Legs", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Strong Swimmer", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Strong-minded", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Sturdy", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Suave", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Super Numerate", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Supportive", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Sure Shot", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Surgery", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Tenacious", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Tinker", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Tower of Memories", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Trapper", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Trick Riding", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Tunnel Rat", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Unshakable", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Very Resilient", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Very Strong", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("War Leader", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("War Wizard", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Warrior Born", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Waterman", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Wealthy", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Well-prepared", "--", "-");
INSERT INTO "WarhammerFantasyRoleplayVirtualGM_app_talent" ("name", "description", "max") VALUES ("Witch!", "--", "-");