# Generated by Django 5.0.7 on 2024-08-01 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News2Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.news')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.tag')),
            ],
            options={
                'ordering': ['news'],
            },
        ),
        migrations.AddField(
            model_name='news',
            name='tagss',
            field=models.ManyToManyField(blank=True, through='cms.News2Tag', to='cms.tag'),
        ),
    ]
