# Generated by Django 5.0.7 on 2024-08-02 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_alter_news_contents'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='yt_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
