# Generated by Django 5.0.7 on 2024-08-05 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_news_yt_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='yt_id',
            new_name='internal_id',
        ),
        migrations.AddField(
            model_name='news',
            name='is_yt',
            field=models.BooleanField(blank=True, max_length=50, null=True),
        ),
    ]
