# Generated by Django 5.1 on 2024-09-09 18:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_alter_news_contents_alter_news_datetime_create_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='datetime_create',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 9, 20, 52, 22, 456429), verbose_name='Create Time'),
        ),
    ]
