# Generated by Django 5.1 on 2024-09-15 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0015_alter_news_datetime_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='datetime_create',
            field=models.DateTimeField(verbose_name='Create Time'),
        ),
    ]
