# Generated by Django 3.2.19 on 2024-05-25 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('WarhammerFantasyRoleplayVirtualGM_app', '0057_alter_character_current_wounds'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('species', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='npc_species', to='WarhammerFantasyRoleplayVirtualGM_app.species', verbose_name='Species')),
            ],
        ),
    ]
