# Generated by Django 5.0.6 on 2024-05-25 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WarhammerFantasyRoleplayVirtualGM_NPC', '0004_alter_npc_portrait_npc2skill_npc_skills'),
        ('WarhammerFantasyRoleplayVirtualGM_app', '0058_alter_campaign_notes_alter_character_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='npc',
            name='weapons',
            field=models.ManyToManyField(to='WarhammerFantasyRoleplayVirtualGM_app.weapon', verbose_name='Weapon'),
        ),
        migrations.AlterField(
            model_name='npc',
            name='portrait',
            field=models.ImageField(default='static/page_images/default.png', null=True, upload_to='static/page_images/'),
        ),
        migrations.CreateModel(
            name='NPC2Talent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default='0', verbose_name='Value')),
                ('npc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WarhammerFantasyRoleplayVirtualGM_NPC.npc')),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WarhammerFantasyRoleplayVirtualGM_app.talent')),
            ],
        ),
        migrations.AddField(
            model_name='npc',
            name='talents',
            field=models.ManyToManyField(through='WarhammerFantasyRoleplayVirtualGM_NPC.NPC2Talent', to='WarhammerFantasyRoleplayVirtualGM_app.talent'),
        ),
    ]
