# Generated by Django 5.0.6 on 2024-05-25 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WarhammerFantasyRoleplayVirtualGM_NPC', '0006_alter_npc_skills_alter_npc_talents_alter_npc_weapons'),
        ('WarhammerFantasyRoleplayVirtualGM_app', '0058_alter_campaign_notes_alter_character_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npc',
            name='skills',
            field=models.ManyToManyField(blank=True, null=True, through='WarhammerFantasyRoleplayVirtualGM_NPC.NPC2Skill', to='WarhammerFantasyRoleplayVirtualGM_app.skils'),
        ),
        migrations.AlterField(
            model_name='npc',
            name='talents',
            field=models.ManyToManyField(blank=True, null=True, through='WarhammerFantasyRoleplayVirtualGM_NPC.NPC2Talent', to='WarhammerFantasyRoleplayVirtualGM_app.talent'),
        ),
        migrations.AlterField(
            model_name='npc',
            name='weapons',
            field=models.ManyToManyField(blank=True, null=True, to='WarhammerFantasyRoleplayVirtualGM_app.weapon', verbose_name='Weapon'),
        ),
    ]
