# Generated by Django 5.0.6 on 2024-05-25 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WarhammerFantasyRoleplayVirtualGM_NPC', '0008_alter_npc_skills_alter_npc_talents_alter_npc_weapons'),
        ('WarhammerFantasyRoleplayVirtualGM_app', '0058_alter_campaign_notes_alter_character_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NPC2Trapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default='0', verbose_name='Amount')),
                ('npc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WarhammerFantasyRoleplayVirtualGM_NPC.npc')),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WarhammerFantasyRoleplayVirtualGM_app.trapping')),
            ],
        ),
        migrations.AddField(
            model_name='npc',
            name='trappings',
            field=models.ManyToManyField(blank=True, through='WarhammerFantasyRoleplayVirtualGM_NPC.NPC2Trapping', to='WarhammerFantasyRoleplayVirtualGM_app.trapping'),
        ),
    ]
