# Generated by Django 5.0.6 on 2024-05-25 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WarhammerFantasyRoleplayVirtualGM_NPC', '0009_npc2trapping_npc_trappings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='npc2trapping',
            old_name='talent',
            new_name='trapping',
        ),
    ]
