# Generated by Django 5.0.6 on 2024-05-26 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WarhammerFantasyRoleplayVirtualGM_NPC', '0010_rename_talent_npc2trapping_trapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='npc',
            name='characteristics_m',
            field=models.IntegerField(default='0', verbose_name='Move'),
        ),
        migrations.AddField(
            model_name='npc',
            name='characteristics_w',
            field=models.IntegerField(default='0', verbose_name='Wound'),
        ),
        migrations.AlterField(
            model_name='npc',
            name='characteristics_ws',
            field=models.IntegerField(default='0', verbose_name='Weapon Skill'),
        ),
    ]
