# Generated by Django 5.0.6 on 2024-05-26 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WarhammerFantasyRoleplayVirtualGM_NPC', '0014_creaturetraits'),
    ]

    operations = [
        migrations.CreateModel(
            name='NPC2CreatureTraits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default='0', verbose_name='Amount')),
                ('creatureTraits', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WarhammerFantasyRoleplayVirtualGM_NPC.creaturetraits')),
                ('npc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WarhammerFantasyRoleplayVirtualGM_NPC.npc')),
            ],
        ),
        migrations.AddField(
            model_name='npc',
            name='creatureTraits',
            field=models.ManyToManyField(blank=True, through='WarhammerFantasyRoleplayVirtualGM_NPC.NPC2CreatureTraits', to='WarhammerFantasyRoleplayVirtualGM_NPC.creaturetraits'),
        ),
    ]
