# Generated by Django 5.0.6 on 2024-05-28 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WarhammerFantasyRoleplayVirtualGM_NPC', '0016_alter_npc_name_alter_npc_portrait_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npc2creaturetraits',
            name='amount',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='npc2skill',
            name='value',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='npc2talent',
            name='value',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='npc2trapping',
            name='amount',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Amount'),
        ),
    ]
