# Generated by Django 5.0.6 on 2024-05-28 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WarhammerFantasyRoleplayVirtualGM_NPC', '0017_alter_npc2creaturetraits_amount_and_more'),
        ('WarhammerFantasyRoleplayVirtualGM_app', '0058_alter_campaign_notes_alter_character_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NPC2Spells',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(blank=True, max_length=150, null=True, verbose_name='Value')),
                ('npc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WarhammerFantasyRoleplayVirtualGM_NPC.npc')),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WarhammerFantasyRoleplayVirtualGM_app.spells')),
            ],
        ),
        migrations.AddField(
            model_name='npc',
            name='spells',
            field=models.ManyToManyField(blank=True, through='WarhammerFantasyRoleplayVirtualGM_NPC.NPC2Spells', to='WarhammerFantasyRoleplayVirtualGM_app.spells'),
        ),
    ]
