# Generated by Django 5.0.6 on 2024-05-31 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WarhammerFantasyRoleplayVirtualGM_NPC', '0019_alter_creaturetraits_options_alter_npc_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Adventure',
        ),
    ]
