# Generated by Django 5.0.6 on 2024-06-10 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WarhammerFantasyRoleplayVirtualGM_NPC', '0020_delete_adventure'),
        ('WarhammerFantasyRoleplayVirtualGM_app', '0058_alter_campaign_notes_alter_character_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='npc',
            name='ref',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=models.SET(None), to='WarhammerFantasyRoleplayVirtualGM_app.reference'),
        ),
    ]
