#!/usr/bin/env python3

import sqlite3
import pprint as pp

# https://www.fantasynamegenerators.com/warhammer-high-elf-names.php
# https://www.fantasynamegenerators.com/hobbit-names.php
# https://www.fantasynamegenerators.com/warhammer-dwarf-names.php
# https://www.fantasynamegenerators.com/warhammer-empire-names.php
# https://www.fantasynamegenerators.com/warhammer-wood-elf-names.php


con = sqlite3.connect("../WarhammerFantasyRoleplayVirtualGM_site/db.sqlite3")
cur = con.cursor()

names = {'dwarf-names': {'f': ['Borweh Forgefoot',
                       'Singwat Bouldershaper',
                       'Datre Flamefoot',
                       'Sikko Brownward',
                       'Skibre Nobledreamer',
                       'Bhugmin Fieryshout',
                       'Zhitvi Keenbearer',
                       'Drelve Plainward',
                       'Drigfem Grayhank',
                       'Ghundwet Bluntbough',
                       'Mudwid Coalstrider',
                       'Bhegnud Keenstriker',
                       'Ghudge Hammerback',
                       'Skivruh Grumblehank',
                       'Narzin Grandmore',
                       'Begni Lightpunch',
                       'Sogvim Keenshaper',
                       'Scarwut Mountainshoulder',
                       'Dergru Steelback',
                       'Scugned Truemaster',
                       'Mugwi Caskheart',
                       'Curgre Onyxarmor',
                       'Huthren Deepbrow',
                       'Husgu Silverarmor',
                       'Bhigfuh Bittershield',
                       'Culgru Leadsurge',
                       'Sibron Greataxe',
                       'Bugfi Greatbranch',
                       'Tongri Cliffbeam',
                       'Bargu Regalfinger',
                       'Ghidruh Hillbeam',
                       'Budrin Hammerfists',
                       'Hengrat Blackstrength',
                       'Mukkim Fullhelm',
                       'Zhandwi Keenmark',
                       'Dudwod Graysurge',
                       'Gorget Plainpunch',
                       'Cugmut Brownbeam',
                       'Sasvuh Brokenhead',
                       'Zhesgrud Plainfoot',
                       'Nergwuh Bearfury',
                       'Zhedgeh Noblemark',
                       'Bithrem Greatfury',
                       'Bhekvet Brownbeam',
                       'Silgu Goldenbender',
                       'Ghekvi Keggut',
                       'Hulgre Broadchin',
                       'Zhegnid Metalforce',
                       'Scogne Emberhand',
                       'Detha Cinderheart'],
                 'm': ['Aghugrir Boulderarmor',
                       'Aokadurd Kegkeeper',
                       'Brigac Keenmight',
                       'Daidhograogg Magmaback',
                       'Daulbuguc Merryarm',
                       'Didhurbair Coppershoulder',
                       'Droardoad Strongbearer',
                       'Durain Brokenhead',
                       'Ethroaderd Hillbringer',
                       'Gakekord Rockstrider',
                       'Gegnig Bronzebelt',
                       'Gildord Forgeaxe',
                       'Girbanron Bouldermark',
                       'Grolgrig Ingotbrand',
                       'Khignaogrimm Fuseshout',
                       'Khikorbumm Rumblewalker',
                       'Kragaoc Fierychaser',
                       'Kraldag Mirthbone',
                       'Kraldard Blackbasher',
                       'Maurtok Coalseeker',
                       'Mirben Amberward',
                       'Naothretreg Grudgemark',
                       'Obrat Onyxmore',
                       'Raldec Fieryarm',
                       'Rergolik Flintbelly',
                       'Rilderbog Regalback',
                       'Sindan Merryfist',
                       'Srakan Amberwalker',
                       'Sregdomm Broadarmour',
                       'Srethoghomm Blackgrip',
                       'Srulgaolgric Goldmore',
                       'Strikogit Hammerbeam',
                       'Strorgrag Coalpunch',
                       'Thaket Noblefinger',
                       'Thegot Slenderaxe',
                       'Thognignigg Blackseeker',
                       'Thragrulemm Branebuckle',
                       'Thraorbildaot Fierybasher',
                       'Thrartig Ingotbasher',
                       'Thritrimm Merryshout',
                       'Thulgerterd Rumbleback',
                       'Thuthrir Grandhead',
                       'Traingrac Shatterbuckle',
                       'Trindroc Kragchaser',
                       'Trughegdauk Blackforce',
                       'Trurugrur Steelwalker',
                       'Valugigg Goldenbough',
                       'Vebrig Cragmight',
                       'Zedhongaigg Shatterbluff',
                       'Zerbrokur Cinderforce']},
 'empire-names': {'f': ['Linda Waldmüller',
                        'Yvonne Ehrenberg',
                        'Emery Aach',
                        'Ubalda Mueller',
                        'Bruna Lexer',
                        'Luitgard Weinberger',
                        'Gudrun Scheurer',
                        'Rosamunde Lehmann',
                        'Ehrentraud Muntz',
                        'Schwanhilde Hämmerli',
                        'Loreley Bodenschatz',
                        'Leopoldine Scheidel',
                        'Bliktrud Erdmann',
                        'Ute Rohmer',
                        'Diomira Enzensberger',
                        'Edelgard Tangemann',
                        'Gotlinde Hess',
                        'Bruna Wirz',
                        'Huguette Seitz',
                        'Kirsa Schichau',
                        'Ludwina Hoehmann',
                        'Everarda Kohlmann',
                        'Rosamunde Krukenberg',
                        'Sieghilde Kossmann',
                        'Heilwig Schwefel',
                        'Diethild Richter',
                        'Carla Fleck',
                        'Hildrun Sternberg',
                        'Adolfa Krueger',
                        'Aubrey Palme',
                        'Klothilde Rowohlt',
                        'Hemma Sack',
                        'Margund Hölderlin',
                        'Gunthilde Trausch',
                        'Berta Paasche',
                        'Arda Wachtel',
                        'Huguette Klee',
                        'Diethild Pankau',
                        'Adolfa Teschner',
                        'Carla Dreyfus',
                        'Adelinde Mathesius',
                        'Adela Rheingold',
                        'Wiltrud Ehrhardt',
                        'Wilhelma Nadelman',
                        'Berta Engels',
                        'Hildegard Weideman',
                        'Irma Hönigswald',
                        'Rodina Hegeler',
                        'Kaja Eulenburg',
                        'Brunhilde Schopenhauer'],
                  'm': ['Arnold Raab',
                        'Arnulf Albiker',
                        'Aschwin Maibaum',
                        'Bertrad Grünberg',
                        'Bertram Waldstein',
                        'Dankmar Bechtold',
                        'Dieter Gyrowetz',
                        'Elric Cullmann',
                        'Erhard Lissauer',
                        'Ernest Ammann',
                        'Everard Lindemann',
                        'Farald Brugmann',
                        'Folke Thoma',
                        'Gaston Gottfried',
                        'Gebhard Boll',
                        'Gerfried Waldstein',
                        'Gerwig Mummert',
                        'Helferich Maurer',
                        'Helmer Junkermann',
                        'Hildebrand Kass',
                        'Karl Gerstaecker',
                        'Karl Welker',
                        'Kléber Tausch',
                        'Kraft Specht',
                        'Ludger Clasen',
                        'Luther Thälmann',
                        'Markolf Scheid',
                        'Raban Masing',
                        'Randolf Schultz',
                        'Raymond Hohenstein',
                        'Rayner Hornberger',
                        'Reingard Schrade',
                        'Rembert Hector',
                        'Roger Pracht',
                        'Rudolf Buchtel',
                        'Sachso Heiden',
                        'Siegbert Harnisch',
                        'Sieger Deutschmann',
                        'Sieger Feilhaber',
                        'Siegfried Gutenberg',
                        'Siegmar Schiffer',
                        'Siegward Lohmiller',
                        'Volker Essen',
                        'Volkhard Blecher',
                        'Waldemar Lotz',
                        'Werner Steinhäusser',
                        'Wilburg Uebelhoer',
                        'William Kreutzberg',
                        'Witold Ross',
                        'Wolf Muntz']},
 'high-elf': {'f': ['Aegholfalna The Incredible',
                    'Aezyekha The Majestic',
                    'Alvifane The Artist',
                    'Arnonri The Composed',
                    'Dinaliafi The Great',
                    'Ehida The Humble',
                    'Eimokala The Elegant',
                    'Hadhollanae The Oracle',
                    'Hazarne The Prime',
                    'Hessaza The Admired',
                    'Hirneihha The Executioner',
                    'Homnilma The Valiant',
                    'Ilinryelle The Brilliant',
                    'Illillimye The Loyal',
                    'Khalfissarne The Incredible',
                    'Khevaesemne The Paragon',
                    'Khimmittiakhi The Humble',
                    'Khotassi The Valiant',
                    'Lahaddashi The Exalted',
                    'Lefnikha The Mighty',
                    'Leseta The Strict',
                    'Melroci The Beautiful',
                    'Mialmonri The Angelic',
                    'Naenvyelia The Great',
                    'Nalgyezarlei The Fearless',
                    'Nerornia The Magnificent',
                    'Nialranni The Illustrious',
                    'Oceiriala The Celebrated',
                    'Oddagheshi The Defiant',
                    'Oghasoto The Loremaster',
                    'Otetetta The Just',
                    'Recikhiva The Honored',
                    'Reddati The Artist',
                    'Reikhyeze The Swift',
                    'Relraliarho The Brilliant',
                    'Sanvinvaze The Academic',
                    'Sedielei The Great',
                    'Shalfaddi The Conqueror',
                    'Shanezehie The Sage',
                    'Shaziata The Learned',
                    'Shilmerhami The Poet',
                    'Sholeifnia The Stout',
                    'Simiffi The Stout',
                    'Tamahi The Grand',
                    'Tatedofnie The Expert',
                    'Thaelvahhidia The Artist',
                    'Tidomi The Powerful',
                    'Tikaerae The Merciful',
                    'Yenvifosae The Agile',
                    'Yeroghiva The Radiant'],
              'm': ['Thalen The Honored',
                    'Kiner The Loyal',
                    'Halroc The Impetuous',
                    'Bel-Gaannaec The Austere',
                    'Bel-Zobios The Humble',
                    'Cedyanthus The Incredible',
                    'Bel-Tirdyecrel The Flawless',
                    'Zonanin The Artist',
                    'Salnunthor The Proud',
                    'Bel-Endaclor The Stout',
                    'Dilvac The Incredible',
                    'Aezoc The Guardian',
                    'Sulec The Loremaster',
                    'Dithlar The Exalted',
                    'Bel-Ecran The Pious',
                    'Oberel The Incredible',
                    'Kebradrin The Admired',
                    'Godhadhor The Angel',
                    'Vodhenel The Executioner',
                    'Odalrin The Marvelous',
                    'Harthyar The Wise',
                    'Final The Beast',
                    'Cabris The Prime',
                    'Shartec The Discrete',
                    'Hithlaes The Celebrated',
                    'Bel-Fethothel The Glorious',
                    'Santrodor The Flawless',
                    'Haedirtel The Clever',
                    'Sabezel The Majestic',
                    'Hiontegrus The Serene',
                    'Zozec The Pleasant',
                    'Cogroc The Flawless',
                    'Ebraas The Stout',
                    'Daloc The Swift',
                    'Vaben The Ancient',
                    'Aabalus The Expert',
                    'Bel-Sozolel The Loremaster',
                    'Bel-Cinibor The Specialist',
                    'Bel-Agrantrin The Learned',
                    'Sheburus The Giving',
                    'Dadrir The Oracle',
                    'Vebrel The Angel',
                    'Bel-Yadin The Paragon',
                    'Bel-Sontol The Generous',
                    'Shidel The Honest',
                    'Agrandin The Great',
                    'Dolyarel The Enforcer',
                    'Vaethladhac The Impetuous',
                    'Vaarhyadhin The Blessed',
                    'Solionel The Enforcer']},
 'hobbit-names': {'f': ['Goiswinth Longfoot',
                        'Mariah Underfoot',
                        'Regnetrudis Bunce',
                        'Nora Hlothran',
                        'Ryan Hedgehopper',
                        'Marcovefa Hornblower',
                        'Duenna Underhill',
                        'Adaltrude Sackville-Baggins',
                        'Sestiva Baggins',
                        'Bertha Gamgee',
                        'Burgundefara Townsend',
                        'Samantha Underhill',
                        'Selina Goldworthy',
                        'Rotrud Hornwood',
                        'Radegund Lightfoot',
                        'Regina North-took',
                        'Adelhaid Hopesinger',
                        'Lenora Underburrow',
                        'Nina Took',
                        'Angelica Dewfoot',
                        'Foy Silverstring',
                        'Maxima Brandagamba',
                        'Tavia Goldworthy',
                        'Chrodechildis Brockhouse',
                        'Autumn Fairfoot',
                        'Kestrel Tinyfoot',
                        'Irmingard Longfoot',
                        'Berthegund Bophin',
                        'Bertha Fairfoot',
                        'Scarlet Stumbletoe',
                        'Ingeltrude Gamwich',
                        'Ingeltrud Butcher',
                        'Chlodosind Twofoot',
                        'Theodrada North-took',
                        'Austrechild Brown',
                        'Olivia Bramblethorn',
                        'Donna Goodsong',
                        'Pamphila Goodchild',
                        'Caitlin Fairfoot',
                        'Jenna Hopesinger',
                        'Iridian Proudbottom',
                        'Adallinda Heathertoes',
                        'Grace Roper',
                        'Jessica Goldworthy',
                        'Rotrude Galpsi',
                        'Kaitlyn Proudmead',
                        'Nantechildis Bunce',
                        'Rothaide Hairyfoot',
                        'Neela Oakbottom',
                        'Adallinda Underburrow'],
                  'm': ['Adalhard Sandheaver',
                        'Balbo Butcher',
                        'Baudry Maggot',
                        'Belisarius Goodwort',
                        'Berchar Stoor',
                        'Bilbo Dewfoot',
                        'Bilbo Northtook',
                        'Blutmund Townsend',
                        'Bruno Fleetfoot',
                        'Ceredic Noakesburrow',
                        'Charibert Gawkroger',
                        'Charles Fairfoot',
                        'Childebert Goodsong',
                        'Chramnesind Goodchild',
                        'Clovis Dewfoot',
                        'Dreux Bunce',
                        'Ebbo Gamgee',
                        'Elfstan Brandybuck',
                        'Erard Goodsong',
                        'Folcard Baggins',
                        'Frodo Boulderhill',
                        'Frodo Thornburrow',
                        'Gondulph Galbassi',
                        'Gundolpho Greenhill',
                        'Haiduc Silentfoot',
                        'Harding Longriver',
                        'Heribert Lothran',
                        'Herugar Knotwise',
                        'Hildebold Oldbuck',
                        'Hildifons Stumbletoe',
                        'Huebald Cutton',
                        'Imbert Longriver',
                        'Isengrim Brownlock',
                        'Isumbras Fairfoot',
                        'Laudus Littlefoot',
                        'Lo Farfoot',
                        'Matta Brownlock',
                        'Odo Rumblebelly',
                        'Orderic Took-Brandybuck',
                        'Reginald Hopesinger',
                        'Reginard Gamwich',
                        'Ricbodo Proudfoot',
                        'Rufus Took',
                        'Ted Elvellon',
                        'Theodemir Hlothran',
                        'Theodoric Gamwich',
                        'Togo Lightfoot',
                        'Tomba Proudbody',
                        'Vigor Boulderhill',
                        'Willehad Burrowes']},
 'wood-elf': {'f': ['Asha',
                    'Vaneh',
                    'Drysteh',
                    'Laeten',
                    'Phytris',
                    'Yllyrvyh',
                    'Hyrlalel',
                    'Achelcith',
                    'Yrladih',
                    'Darlashaf',
                    'Thynves',
                    'Seltef',
                    'Phillef',
                    'Venne',
                    'Mede',
                    'Thieccaehhi',
                    'Ychalta',
                    'Dandihe',
                    'Pharreccis',
                    'Phelthaphih',
                    'Nyrif',
                    'Dhalta',
                    'Lerras',
                    'Aeveth',
                    'Vedren',
                    'Nerledis',
                    'Aelelthes',
                    'Phanerle',
                    'Hacienve',
                    'Dicastra',
                    'Dratra',
                    'Qese',
                    'Lide',
                    'Ytraf',
                    'Halyf',
                    'Fyltharlan',
                    'Yhietha',
                    'Nycece',
                    'Thydesas',
                    'Itrastath',
                    'Letral',
                    'Yielvyf',
                    'Thalni',
                    'Fadre',
                    'Dhysyn',
                    'Ylthystrif',
                    'Sylcepha',
                    'Hestery',
                    'Ninylthe',
                    'Ylsierre'],
              'm': ['Aalcu',
                    'Acco',
                    'Asratrian',
                    'Cadocas',
                    'Caelcodis',
                    'Coslos',
                    'Dacrallaan',
                    'Dastidut',
                    'Dhioron',
                    'Dhoslun',
                    'Dolostath',
                    'Dorat',
                    'Godath',
                    'Iarton',
                    'Iathikkas',
                    'Ilath',
                    'Ioccargaes',
                    'Kaada',
                    'Khalolto',
                    'Khiocro',
                    'Khukosta',
                    'Kizcat',
                    'Kudat',
                    'Kulacut',
                    'Sculgo',
                    'Stracalos',
                    'Straeru',
                    'Strulioth',
                    'Takikoc',
                    'Thaakilkuth',
                    'Thado',
                    'Thados',
                    'Thiakkurcat',
                    'Thiokion',
                    'Tholgiakat',
                    'Thuciolgis',
                    'Toca',
                    'Totrorlon',
                    'Traelgo',
                    'Trorartut',
                    'Trothaltac',
                    'Trudu',
                    'Turcilae',
                    'Uku',
                    'Urazcu',
                    'Vadat',
                    'Vullaltas',
                    'Zakia',
                    'Zialtalgaet',
                    'Zokadrae']}
    }

species2Id = {"wood-elf":5, "hobbit-names":3, "high-elf":1, "dwarf-names":4, "empire-names":2}


for species, val in names.items():
    for sex, name_list in names[species].items():
        for name in name_list:
            query = 'INSERT INTO WarhammerFantasyRoleplayVirtualGM_app_examplename (species_id, name , sex) VALUES( {}, "{}" , "{}");'.format(species2Id[species], name, sex)
            print(query)
            cur.execute(query)

con.commit()


